import { mockParkingFacilities } from '@/mock/parking';
import { storageService } from '@/services/storage-service';
import { vehicleService } from '@/services/vehicle-service';
import { parkingSessionConfig } from '@/config/parking-session';
import { Booking, BookingCancellation, BookingCategory, BookingDraft, BookingExtension, BookingPriceBreakdown, CancellationReason, CancellationRefundBreakdown, ExtensionPriceBreakdown, ParkingSlot, Payment, PaymentMethod, PaymentStatus, Refund } from '@/types/domain';
import { calculateParkingPrice } from '@/utils/booking-price';
import { isWithinParkingHours } from '@/utils/booking-time';
import { getBookingTemporalStatus } from '@/utils/booking-lifecycle';
import { calculateCancellationRefund, canCancelBooking, categorizeBooking } from '@/utils/booking-history';
import { paymentService } from '@/services/payment-service';

const wait = () => new Promise<void>((resolve) => setTimeout(resolve, 420));
const slotTypes = ['standard', 'standard', 'standard', 'ev', 'accessible', 'premium'] as const;
function makeSlots(parkingId: string): ParkingSlot[] { return ['A', 'B', 'C'].flatMap((section, sectionIndex) => Array.from({ length: 12 }, (_, index) => { const number = index + 1; const type = slotTypes[(index + sectionIndex) % slotTypes.length]; const generatedStatus = (index + sectionIndex * 2) % 8 === 0 ? 'occupied' : (index + sectionIndex) % 11 === 0 ? 'reserved' : 'available'; const status = section === 'A' && number === 12 ? 'available' : generatedStatus; return { id: `${parkingId}-${section}${String(number).padStart(2, '0')}`, label: `${section}${String(number).padStart(2, '0')}`, section, status, type, level: 'Level 1' }; })); }
export const bookingService = {
  async checkAvailability(parkingId: string, arrival: string, exit: string) { await wait(); const facility = mockParkingFacilities.find((item) => item.id === parkingId); const validRange = new Date(exit) > new Date(arrival); return { available: Boolean(facility && facility.availableSlots > 0 && validRange), availableSlots: facility?.availableSlots ?? 0 }; },
  async getAvailableSlots(parkingId: string, arrival: string, exit: string) { const check = await this.checkAvailability(parkingId, arrival, exit); if (!check.available) return []; return makeSlots(parkingId); },
  async isSlotAvailable(parkingId: string, slotId: string, arrival: string, exit: string) { const slots = await this.getAvailableSlots(parkingId, arrival, exit); return slots.some((slot) => slot.id === slotId && slot.status === 'available'); },
  calculateEstimate(parkingId: string, durationMinutes: number) { const facility = mockParkingFacilities.find((item) => item.id === parkingId); if (!facility) return 0; return calculateParkingPrice(facility.pricing, facility.pricePerHour, durationMinutes); },
  async getBookings() { return (await storageService.readJson<Booking[]>(storageService.keys.bookings)) ?? []; },
  async getBookingById(id: string) { return (await this.getBookings()).find((booking) => booking.id === id) ?? null; },
  async getBookingsByCategory(category: BookingCategory) { return (await this.getBookings()).filter((booking) => categorizeBooking(booking) === category); },
  async getActiveBookings() { return (await this.getBookings()).filter((booking) => booking.status !== 'cancelled' && ['active', 'endingSoon'].includes(getBookingTemporalStatus(booking))); },
  async getUpcomingBookings() { return this.getBookingsByCategory('upcoming'); },
  async getCompletedBookings() { return this.getBookingsByCategory('completed'); },
  async getCancelledBookings() { return this.getBookingsByCategory('cancelled'); },
  async getPayments(bookingId: string) { return ((await storageService.readJson<Payment[]>(storageService.keys.payments)) ?? []).filter((item) => item.bookingId === bookingId); },
  async getCancellation(bookingId: string) { return ((await storageService.readJson<BookingCancellation[]>(storageService.keys.bookingCancellations)) ?? []).find((item) => item.bookingId === bookingId) ?? null; },
  async getRefund(bookingId: string) { return ((await storageService.readJson<Refund[]>(storageService.keys.refunds)) ?? []).find((item) => item.bookingId === bookingId) ?? null; },
  async createBooking(draft: BookingDraft, breakdown: BookingPriceBreakdown, payment: { id: string; status: PaymentStatus; method: PaymentMethod; amount: number; transactionReference: string; createdAt: string }, userId = 'mock-user') { if (payment.status !== 'success' || !draft.vehicleId || !draft.arrivalDateTime || !draft.exitDateTime || !draft.slotPreference) throw new Error('A successful payment and complete booking draft are required.'); const facility = mockParkingFacilities.find((item) => item.id === draft.parkingId); const vehicle = await vehicleService.getVehicleById(draft.vehicleId); if (!facility || !vehicle) throw new Error('Booking details are unavailable.'); const now = new Date(); const id = `booking-${Date.now()}`; const bookingReference = `PK-${String(now.getFullYear()).slice(-2)}${String(now.getMonth() + 1).padStart(2, '0')}${String(now.getDate()).padStart(2, '0')}-${Math.random().toString(36).slice(2, 6).toUpperCase()}`; const booking: Booking = { id, bookingReference, userId, facilityId: facility.id, vehicleId: vehicle.id, status: 'confirmed', entryTime: draft.arrivalDateTime, exitTime: draft.exitDateTime, durationMinutes: draft.durationMinutes, slotId: draft.selectedSlotId, slotPreference: draft.slotPreference, totalAmount: breakdown.totalAmount, priceBreakdown: breakdown, paymentId: payment.id, paymentStatus: payment.status, createdAt: now.toISOString(), parkingName: facility.name, parkingAddress: facility.address, vehicleRegistration: vehicle.registrationNumber }; const persistedPayment: Payment = { ...payment, bookingId: id, currency: 'INR' }; const [bookings, payments] = await Promise.all([this.getBookings(), storageService.readJson<Payment[]>(storageService.keys.payments)]); await Promise.all([storageService.writeJson(storageService.keys.bookings, [booking, ...bookings]), storageService.writeJson(storageService.keys.payments, [persistedPayment, ...(payments ?? [])])]); return booking; },
  async getExtensions(bookingId: string) { return ((await storageService.readJson<BookingExtension[]>(storageService.keys.bookingExtensions)) ?? []).filter((item) => item.bookingId === bookingId); },
  calculateExtensionPrice(booking: Booking, addedMinutes: number): ExtensionPriceBreakdown { const facility = mockParkingFacilities.find((item) => item.id === booking.facilityId); if (!facility) return { additionalParkingCharge: 0, extensionFee: 0, taxAmount: 0, discountAmount: 0, totalAmount: 0, currency: 'INR' }; const previous = calculateParkingPrice(facility.pricing, facility.pricePerHour, booking.durationMinutes); const updated = calculateParkingPrice(facility.pricing, facility.pricePerHour, booking.durationMinutes + addedMinutes); const additionalParkingCharge = Math.max(0, updated - previous); const extensionFee = parkingSessionConfig.extensionFee; return { additionalParkingCharge, extensionFee, taxAmount: 0, discountAmount: 0, totalAmount: additionalParkingCharge + extensionFee, currency: 'INR' }; },
  async checkExtensionAvailability(bookingId: string, newExitDateTime: string) { await wait(); const booking = await this.getBookingById(bookingId); if (!booking) return { available: false, message: 'Booking not found.' }; const facility = mockParkingFacilities.find((item) => item.id === booking.facilityId); if (!facility) return { available: false, message: 'Parking facility unavailable.' }; const newExit = new Date(newExitDateTime); const addedMinutes = Math.round((newExit.getTime() - new Date(booking.exitTime).getTime()) / 60_000); const totalDuration = Math.round((newExit.getTime() - new Date(booking.entryTime).getTime()) / 60_000); if (addedMinutes <= 0 || addedMinutes > parkingSessionConfig.maxExtensionMinutes) return { available: false, message: `Extensions are limited to ${parkingSessionConfig.maxExtensionMinutes} minutes.` }; if (totalDuration > parkingSessionConfig.maxStayMinutes) return { available: false, message: "You can't extend beyond the maximum parking duration." }; if (!isWithinParkingHours(facility, new Date(booking.entryTime), newExit)) return { available: false, message: `This parking facility closes at ${facility.closeTime}.` }; if (booking.slotPreference === 'specific' && booking.slotId && !(await this.isSlotAvailable(facility.id, booking.slotId, booking.exitTime, newExitDateTime))) return { available: false, message: "Your current slot can't be extended for that time." }; const capacity = await this.checkAvailability(facility.id, booking.exitTime, newExitDateTime); return capacity.available ? { available: true, message: '' } : { available: false, message: 'No spaces are available for that extension.' }; },
  async applyExtension(bookingId: string, addedMinutes: number, payment: { id: string; status: PaymentStatus; method: PaymentMethod; amount: number; transactionReference: string; createdAt: string }) { if (payment.status !== 'success') throw new Error('Extension payment did not succeed.'); const bookings = await this.getBookings(); const booking = bookings.find((item) => item.id === bookingId); if (!booking) throw new Error('Booking not found.'); const previousExitDateTime = booking.exitTime; const newExit = new Date(new Date(previousExitDateTime).getTime() + addedMinutes * 60_000).toISOString(); const availability = await this.checkExtensionAvailability(bookingId, newExit); if (!availability.available) throw new Error(availability.message); const pricing = this.calculateExtensionPrice(booking, addedMinutes); const updated: Booking = { ...booking, exitTime: newExit, durationMinutes: booking.durationMinutes + addedMinutes, totalAmount: booking.totalAmount + pricing.totalAmount, priceBreakdown: { ...booking.priceBreakdown, parkingCharge: booking.priceBreakdown.parkingCharge + pricing.additionalParkingCharge, convenienceFee: booking.priceBreakdown.convenienceFee + pricing.extensionFee, totalAmount: booking.priceBreakdown.totalAmount + pricing.totalAmount } }; const extension: BookingExtension = { id: `extension-${Date.now()}`, bookingId, previousExitDateTime, newExitDateTime: newExit, addedMinutes, amount: pricing.totalAmount, paymentId: payment.id, createdAt: new Date().toISOString() }; const persistedPayment: Payment = { ...payment, bookingId, currency: 'INR' }; const [extensions, payments] = await Promise.all([storageService.readJson<BookingExtension[]>(storageService.keys.bookingExtensions), storageService.readJson<Payment[]>(storageService.keys.payments)]); await Promise.all([storageService.writeJson(storageService.keys.bookings, bookings.map((item) => item.id === bookingId ? updated : item)), storageService.writeJson(storageService.keys.bookingExtensions, [extension, ...(extensions ?? [])]), storageService.writeJson(storageService.keys.payments, [persistedPayment, ...(payments ?? [])])]); return updated; },
  async cancelBooking(input: { bookingId: string; reason: CancellationReason; reasonDetails?: string; refundCalculation: CancellationRefundBreakdown }) {
    const bookings = await this.getBookings();
    const booking = bookings.find((item) => item.id === input.bookingId);
    if (!booking) throw new Error('Booking not found.');
    if (!canCancelBooking(booking)) throw new Error('This booking can no longer be cancelled.');
    if (await this.getCancellation(booking.id)) throw new Error('This booking has already been cancelled.');
    const freshCalculation = calculateCancellationRefund(booking);
    const refundCalculation = { ...freshCalculation, refundAmount: Math.min(freshCalculation.refundAmount, input.refundCalculation.refundAmount) };
    const payments = await this.getPayments(booking.id);
    const originalPayment = payments.find((payment) => payment.id === booking.paymentId && payment.status === 'success');
    if (!originalPayment) throw new Error('The original payment could not be found.');
    const refund = refundCalculation.refundAmount > 0 ? await paymentService.processMockRefund(originalPayment, refundCalculation.refundAmount) : null;
    const cancellation: BookingCancellation = { id: `cancellation-${Date.now()}`, bookingId: booking.id, cancelledAt: new Date().toISOString(), reason: input.reason, reasonDetails: input.reasonDetails?.trim() || undefined, cancellationFee: refundCalculation.cancellationFee, refundAmount: refundCalculation.refundAmount, refundStatus: refund?.status ?? 'notRequired', refundId: refund?.id };
    const updatedBooking: Booking = { ...booking, status: 'cancelled' };
    const [cancellations, refunds] = await Promise.all([storageService.readJson<BookingCancellation[]>(storageService.keys.bookingCancellations), storageService.readJson<Refund[]>(storageService.keys.refunds)]);
    await Promise.all([storageService.writeJson(storageService.keys.bookings, bookings.map((item) => item.id === booking.id ? updatedBooking : item)), storageService.writeJson(storageService.keys.bookingCancellations, [cancellation, ...(cancellations ?? [])]), refund ? storageService.writeJson(storageService.keys.refunds, [refund, ...(refunds ?? [])]) : Promise.resolve()]);
    return { booking: updatedBooking, cancellation, refund };
  },
  async createBookingFromPrevious(bookingId: string): Promise<BookingDraft> {
    const booking = await this.getBookingById(bookingId);
    if (!booking) throw new Error('Booking not found.');
    const facility = mockParkingFacilities.find((item) => item.id === booking.facilityId);
    if (!facility) throw new Error('This parking location is no longer available.');
    const vehicle = await vehicleService.getVehicleById(booking.vehicleId);
    return { parkingId: booking.facilityId, vehicleId: vehicle?.id ?? null, arrivalDateTime: null, durationMinutes: booking.durationMinutes, exitDateTime: null, selectedSlotId: null, slotPreference: null, estimatedParkingAmount: this.calculateEstimate(booking.facilityId, booking.durationMinutes), couponCode: null };
  },
};
