import { Ionicons } from '@expo/vector-icons';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Booking, BookingCategory } from '@/types/domain';
import { formatBookingDateTime, formatTime } from '@/utils/booking-time';
import { formatCurrency } from '@/utils/parking-formatters';
import { colors, radius, shadows, spacing, typography } from '@/theme/tokens';

type Props = { booking: Booking; category: BookingCategory; onPress: () => void; onBookAgain?: () => void; onDirections?: () => void; };
const labels: Record<BookingCategory, string> = { upcoming: 'UPCOMING', active: 'PARKING ACTIVE', completed: 'COMPLETED', cancelled: 'CANCELLED' };
const badgeStyles: Record<BookingCategory, { backgroundColor: string; color: string }> = { upcoming: { backgroundColor: colors.primarySoft, color: colors.primary }, active: { backgroundColor: colors.successSoft, color: colors.success }, completed: { backgroundColor: colors.surfaceMuted, color: colors.textSecondary }, cancelled: { backgroundColor: colors.errorSoft, color: colors.error } };

export function BookingCard({ booking, category, onPress, onBookAgain, onDirections }: Props) {
  const slot = booking.slotPreference === 'any' ? 'Slot on arrival' : booking.slotId?.split('-').at(-1) ?? 'Slot pending';
  return <Pressable accessibilityRole="button" accessibilityLabel={`View ${booking.parkingName} booking`} onPress={onPress} style={({ pressed }) => [styles.card, pressed && styles.pressed]}><View style={styles.top}><View style={[styles.badge, { backgroundColor: badgeStyles[category].backgroundColor }]}><Text style={[styles.badgeText, { color: badgeStyles[category].color }]}>{labels[category]}</Text></View><Text style={styles.amount}>{formatCurrency(booking.totalAmount)}</Text></View><Text numberOfLines={1} style={styles.name}>{booking.parkingName}</Text><Text style={styles.date}>{formatBookingDateTime(booking.entryTime)}</Text><Text style={styles.time}>{formatTime(booking.entryTime)} – {formatTime(booking.exitTime)}</Text><View style={styles.meta}><Text style={styles.metaText}>{booking.vehicleRegistration}</Text><Text style={styles.dot}>•</Text><Text style={styles.metaText}>{slot}</Text></View><Text style={styles.reference}>{booking.bookingReference}</Text>{(category === 'completed' || category === 'cancelled' || (category === 'upcoming' && onDirections)) ? <View style={styles.actions}>{category === 'upcoming' && onDirections ? <Pressable accessibilityRole="button" accessibilityLabel="Get directions" onPress={(event) => { event.stopPropagation(); onDirections(); }} style={styles.action}><Ionicons name="navigate-outline" size={16} color={colors.primary} /><Text style={styles.actionText}>Directions</Text></Pressable> : null}{(category === 'completed' || category === 'cancelled') && onBookAgain ? <Pressable accessibilityRole="button" accessibilityLabel="Book again" onPress={(event) => { event.stopPropagation(); onBookAgain(); }} style={styles.action}><Ionicons name="repeat-outline" size={16} color={colors.primary} /><Text style={styles.actionText}>Book again</Text></Pressable> : null}</View> : null}</Pressable>;
}
const styles = StyleSheet.create({ card: { padding: spacing.lg, borderRadius: radius.lg, backgroundColor: colors.surface, ...shadows.card }, pressed: { opacity: 0.82 }, top: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, badge: { paddingHorizontal: spacing.sm, paddingVertical: 4, borderRadius: radius.full }, badgeText: { ...typography.captionStrong, letterSpacing: 0.45 }, amount: { ...typography.bodyStrong, color: colors.textPrimary }, name: { ...typography.title3, color: colors.textPrimary, marginTop: spacing.md }, date: { ...typography.bodySmall, color: colors.textSecondary, marginTop: spacing.sm }, time: { ...typography.bodyStrong, color: colors.textPrimary, marginTop: 2 }, meta: { flexDirection: 'row', alignItems: 'center', gap: spacing.xs, marginTop: spacing.sm }, metaText: { ...typography.bodySmall, color: colors.textSecondary }, dot: { color: colors.textTertiary }, reference: { ...typography.caption, color: colors.textTertiary, marginTop: spacing.sm }, actions: { flexDirection: 'row', gap: spacing.sm, marginTop: spacing.md }, action: { flexDirection: 'row', alignItems: 'center', gap: 5, paddingVertical: spacing.sm, paddingHorizontal: spacing.md, borderRadius: radius.full, backgroundColor: colors.primarySoft }, actionText: { ...typography.captionStrong, color: colors.primary } });
