import { Href, router, useLocalSearchParams } from 'expo-router';
import { useEffect, useState } from 'react';
import { ActivityIndicator, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { PrimaryButton } from '@/components/ui/primary-button';
import { bookingService } from '@/services/booking-service';
import { BookingCancellation } from '@/types/domain';
import { formatCurrency } from '@/utils/parking-formatters';
import { colors, radius, spacing, typography } from '@/theme/tokens';

export default function CancellationSuccessScreen() { const { id } = useLocalSearchParams<{ id: string }>(); const [cancellation, setCancellation] = useState<BookingCancellation | null>(null); useEffect(() => { void bookingService.getCancellation(id).then(setCancellation); }, [id]); if (!cancellation) return <SafeAreaView style={styles.screen}><ActivityIndicator color={colors.primary} /></SafeAreaView>; const refundText = cancellation.refundStatus === 'refunded' ? 'Refund processed successfully.' : cancellation.refundStatus === 'failed' ? 'Refund needs attention. Your booking remains cancelled.' : 'No refund was required.'; return <SafeAreaView style={styles.screen}><View style={styles.content}><View style={styles.icon}><Text style={styles.iconText}>✓</Text></View><Text style={styles.title}>Booking Cancelled</Text><Text style={styles.subtitle}>{refundText}</Text><View style={styles.refund}><Text style={styles.refundLabel}>Refund</Text><Text style={styles.refundAmount}>{formatCurrency(cancellation.refundAmount)}</Text><Text style={styles.refundStatus}>{cancellation.refundStatus === 'refunded' ? 'REFUNDED' : cancellation.refundStatus === 'failed' ? 'REFUND FAILED' : 'NO REFUND'}</Text></View><PrimaryButton label="View Booking" onPress={() => router.replace(`/booking-details?id=${id}` as Href)} /><PrimaryButton label="Find Parking" onPress={() => router.replace('/results' as Href)} style={styles.find} /></View></SafeAreaView>; }
const styles = StyleSheet.create({ screen: { flex: 1, justifyContent: 'center', padding: spacing.lg, backgroundColor: colors.background }, content: { gap: spacing.lg, alignItems: 'center' }, icon: { width: 76, height: 76, borderRadius: radius.full, justifyContent: 'center', alignItems: 'center', backgroundColor: colors.successSoft }, iconText: { fontSize: 38, fontWeight: '700', color: colors.success }, title: { ...typography.title1, color: colors.textPrimary }, subtitle: { ...typography.body, color: colors.textSecondary, textAlign: 'center' }, refund: { width: '100%', alignItems: 'center', gap: spacing.xs, padding: spacing.xl, borderRadius: radius.lg, backgroundColor: colors.surface }, refundLabel: { ...typography.bodySmall, color: colors.textSecondary }, refundAmount: { ...typography.display, color: colors.textPrimary }, refundStatus: { ...typography.captionStrong, color: colors.success, letterSpacing: 0.6 }, find: { width: '100%', backgroundColor: colors.surfaceMuted } });
