import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { PrimaryButton } from '@/components/ui/primary-button';
import { colors, radius, spacing, typography } from '@/theme/tokens';

const faqs = [['How do I reserve parking?', 'Choose a parking location, select your vehicle, time and slot, then complete the mock checkout.'], ['How do I cancel a booking?', 'Open My Bookings, select an eligible upcoming booking and review the cancellation refund before confirming.'], ['When will I receive a refund?', 'Mock refunds are recorded immediately in this development build.'], ['How do I extend parking?', 'Open Active Parking and choose Extend Parking while your session is active.'], ['Where can I find my QR pass?', 'Open your booking details and select View QR Pass.']];
export default function HelpScreen() { const [open, setOpen] = useState<number | null>(0); return <SafeAreaView style={styles.screen}><ScrollView contentContainerStyle={styles.content}><Text style={styles.title}>Help & Support</Text><Text style={styles.intro}>Find quick answers or send our support team a request.</Text><Text style={styles.heading}>FREQUENTLY ASKED QUESTIONS</Text><View style={styles.faqList}>{faqs.map(([question, answer], index) => <Pressable key={question} accessibilityRole="button" accessibilityState={{ expanded: open === index }} onPress={() => setOpen(open === index ? null : index)} style={[styles.faq, index < faqs.length - 1 && styles.divider]}><View style={styles.questionRow}><Text style={styles.question}>{question}</Text><Ionicons name={open === index ? 'chevron-up' : 'chevron-down'} size={18} color={colors.textSecondary} /></View>{open === index ? <Text style={styles.answer}>{answer}</Text> : null}</Pressable>)}</View><Text style={styles.heading}>GET IN TOUCH</Text><View style={styles.contact}><View style={styles.contactIcon}><Ionicons name="mail-outline" size={20} color={colors.primary} /></View><View style={styles.flex}><Text style={styles.contactTitle}>Contact Support</Text><Text style={styles.answer}>Support contact is not configured for this development build.</Text></View></View><PrimaryButton label="Report a Problem" icon="flag-outline" onPress={() => router.push('/support-request' as never)} /><PrimaryButton label="My Support Requests" variant="secondary" icon="chatbubble-outline" onPress={() => router.push('/support-requests' as never)} /></ScrollView></SafeAreaView>; }
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.background }, content: { padding: spacing.lg, gap: spacing.md, paddingBottom: spacing.xxxl }, title: { ...typography.title1, color: colors.textPrimary }, intro: { ...typography.bodySmall, color: colors.textSecondary }, heading: { ...typography.captionStrong, color: colors.textTertiary, letterSpacing: 0.5, marginTop: spacing.md }, faqList: { borderWidth: 1, borderColor: colors.borderSubtle, borderRadius: radius.lg, overflow: 'hidden', backgroundColor: colors.surface }, faq: { padding: spacing.md }, divider: { borderBottomWidth: 1, borderBottomColor: colors.borderSubtle }, questionRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.md }, question: { ...typography.bodyStrong, flex: 1, color: colors.textPrimary }, answer: { ...typography.bodySmall, color: colors.textSecondary, marginTop: spacing.sm, lineHeight: 20 }, contact: { flexDirection: 'row', gap: spacing.md, padding: spacing.md, borderWidth: 1, borderColor: colors.borderSubtle, borderRadius: radius.lg, backgroundColor: colors.surface }, contactIcon: { width: 38, height: 38, alignItems: 'center', justifyContent: 'center', borderRadius: radius.md, backgroundColor: colors.primarySoft }, flex: { flex: 1 }, contactTitle: { ...typography.bodyStrong, color: colors.textPrimary } });
