import { Ionicons } from '@expo/vector-icons';
import { Href, router, useFocusEffect } from 'expo-router';
import { useCallback, useState } from 'react';
import { FlatList, Pressable, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { EmptyState } from '@/components/ui/empty-state';
import { notificationService } from '@/services/notification-service';
import { AppNotification } from '@/types/domain';
import { formatBookingDateTime } from '@/utils/booking-time';
import { colors, radius, spacing, typography } from '@/theme/tokens';

export default function NotificationsScreen() { const [items, setItems] = useState<AppNotification[]>([]); const load = useCallback(async () => setItems(await notificationService.getNotifications()), []); useFocusEffect(useCallback(() => { void load(); }, [load])); const unreadCount = items.filter((item) => !item.isRead).length; const open = async (item: AppNotification) => { await notificationService.markAsRead(item.id); if (item.bookingId) router.push(`/booking-details?id=${item.bookingId}` as Href); else if (item.parkingId) router.push(`/parking/${item.parkingId}` as Href); else if (item.type === 'offer') router.push('/offers' as Href); else void load(); }; return <SafeAreaView style={styles.screen}><View style={styles.header}><View><Text style={styles.title}>Notifications</Text>{unreadCount ? <Text style={styles.count}>{unreadCount} unread</Text> : null}</View>{unreadCount ? <Pressable accessibilityRole="button" accessibilityLabel="Mark all notifications as read" onPress={() => void notificationService.markAllAsRead().then(load)} style={({ pressed }) => [styles.read, pressed && styles.pressed]}><Text style={styles.readText}>Mark all read</Text></Pressable> : null}</View><FlatList data={items} keyExtractor={(item) => item.id} contentContainerStyle={items.length ? styles.list : styles.empty} renderItem={({ item }) => <NotificationRow item={item} onPress={open} />} ListEmptyComponent={<EmptyState icon="notifications-off-outline" title="You're all caught up." description="Booking updates and parking reminders will appear here." />} /></SafeAreaView>; }
function NotificationRow({ item, onPress }: { item: AppNotification; onPress: (item: AppNotification) => void }) { return <Pressable accessibilityRole="button" accessibilityLabel={`${item.isRead ? '' : 'Unread '}${item.title}`} onPress={() => void onPress(item)} style={({ pressed }) => [styles.row, !item.isRead && styles.unread, pressed && styles.pressed]}><View style={styles.icon}><Ionicons name={item.isRead ? 'notifications-outline' : 'notifications'} size={19} color={colors.primary} /></View><View style={styles.flex}><Text numberOfLines={1} style={[styles.rowTitle, !item.isRead && styles.strong]}>{item.title}</Text><Text numberOfLines={2} style={styles.body}>{item.body}</Text><Text style={styles.time}>{formatBookingDateTime(item.createdAt)}</Text></View>{!item.isRead ? <View style={styles.dot} /> : null}</Pressable>; }
const styles = StyleSheet.create({ screen: { flex: 1, padding: spacing.lg, backgroundColor: colors.background }, header: { minHeight: 52, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: spacing.lg }, title: { ...typography.title1, color: colors.textPrimary }, count: { ...typography.caption, color: colors.textSecondary, marginTop: 2 }, read: { paddingHorizontal: spacing.sm, paddingVertical: spacing.sm, borderRadius: radius.full, backgroundColor: colors.primarySoft }, readText: { ...typography.captionStrong, color: colors.primary }, list: { gap: 0, paddingBottom: spacing.xxxl, borderRadius: radius.lg, overflow: 'hidden', backgroundColor: colors.surface }, empty: { flexGrow: 1 }, row: { minHeight: 82, flexDirection: 'row', alignItems: 'flex-start', gap: spacing.sm, padding: spacing.md, borderBottomWidth: 1, borderBottomColor: colors.borderSubtle, backgroundColor: colors.surface }, unread: { backgroundColor: colors.primarySoft }, icon: { width: 34, height: 34, alignItems: 'center', justifyContent: 'center', borderRadius: radius.full, backgroundColor: colors.surface }, flex: { flex: 1 }, rowTitle: { ...typography.bodyStrong, color: colors.textPrimary }, strong: { fontWeight: '700' }, body: { ...typography.bodySmall, color: colors.textSecondary, marginTop: 2 }, time: { ...typography.caption, color: colors.textTertiary, marginTop: spacing.xs }, dot: { width: 7, height: 7, borderRadius: radius.full, backgroundColor: colors.primary, marginTop: 6 }, pressed: { opacity: 0.82 } });
