import { Href, router } from 'expo-router';
import { useEffect, useState } from 'react';
import { FlatList, Pressable, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { EmptyState } from '@/components/ui/empty-state';
import { couponService } from '@/services/coupon-service';
import { Coupon } from '@/types/domain';
import { formatCurrency } from '@/utils/parking-formatters';
import { colors, radius, shadows, spacing, typography } from '@/theme/tokens';

export default function OffersScreen() { const [offers, setOffers] = useState<Coupon[]>([]); useEffect(() => { void couponService.getAvailableCoupons().then(setOffers); }, []); return <SafeAreaView style={styles.screen}><Text style={styles.title}>Offers & Coupons</Text><FlatList data={offers} keyExtractor={(item) => item.id} contentContainerStyle={offers.length ? styles.list : styles.empty} renderItem={({ item }) => <OfferCard item={item} />} ListEmptyComponent={<EmptyState icon="pricetag-outline" title="No offers available right now." description="New parking offers will appear here." />} /></SafeAreaView>; }
function OfferCard({ item }: { item: Coupon }) { return <View style={styles.card}><View style={styles.codeRow}><Text style={styles.code}>{item.code}</Text><View style={styles.status}><Text style={styles.statusText}>Available</Text></View></View><Text style={styles.name}>{item.title}</Text><Text style={styles.description}>{item.description}</Text><Text style={styles.meta}>Minimum booking {formatCurrency(item.minimumBookingAmount)}</Text><View style={styles.footer}><Text style={styles.saving}>Save up to {formatCurrency(item.maximumDiscount)}</Text><Pressable accessibilityRole="button" accessibilityLabel={`Use ${item.code}`} onPress={() => router.push('/results' as Href)} style={({ pressed }) => [styles.use, pressed && styles.pressed]}><Text style={styles.useText}>Use Offer</Text></Pressable></View></View>; }
const styles = StyleSheet.create({ screen: { flex: 1, padding: spacing.lg, backgroundColor: colors.background }, title: { ...typography.title1, color: colors.textPrimary, marginBottom: spacing.lg }, list: { gap: spacing.md, paddingBottom: spacing.xxxl }, empty: { flexGrow: 1 }, card: { gap: spacing.sm, padding: spacing.lg, borderWidth: 1, borderColor: colors.borderSubtle, borderRadius: radius.lg, backgroundColor: colors.surface, ...shadows.card }, codeRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, code: { ...typography.captionStrong, color: colors.primary, letterSpacing: 1 }, status: { paddingHorizontal: spacing.sm, paddingVertical: 4, borderRadius: radius.full, backgroundColor: colors.successSoft }, statusText: { ...typography.captionStrong, color: colors.success }, name: { ...typography.title3, color: colors.textPrimary }, description: { ...typography.bodySmall, color: colors.textSecondary }, meta: { ...typography.caption, color: colors.textTertiary, marginTop: spacing.xs }, footer: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: spacing.sm }, saving: { ...typography.bodyStrong, color: colors.textPrimary }, use: { paddingHorizontal: spacing.md, paddingVertical: spacing.sm, borderRadius: radius.full, backgroundColor: colors.primarySoft }, useText: { ...typography.captionStrong, color: colors.primary }, pressed: { opacity: 0.82 } });
