import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { authService } from '@/services/auth-service';
import { locationService } from '@/services/location-service';
import { colors, radius, spacing, typography } from '@/theme/tokens';

export default function PrivacySecurityScreen() { const remove = () => Alert.alert('Delete your account?', 'Your local ParkEase account information and saved user data will be removed from this development installation. This is local/mock deletion, not production backend deletion.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Continue', style: 'destructive', onPress: () => Alert.alert('Confirm local deletion', 'This cannot be undone on this device.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Delete Account', style: 'destructive', onPress: () => void authService.deleteLocalAccount().then(() => router.replace('/welcome' as never)) }]) }]); return <SafeAreaView style={styles.screen}><Text style={styles.title}>Privacy & Security</Text><Text style={styles.heading}>PERMISSIONS</Text><View style={styles.card}><Pressable accessibilityRole="button" onPress={() => void locationService.openSettings()} style={styles.row}><View style={styles.icon}><Ionicons name="location-outline" size={19} color={colors.primary} /></View><View style={styles.flex}><Text style={styles.rowTitle}>Location access</Text><Text style={styles.copy}>Manage access in device settings</Text></View><Ionicons name="chevron-forward" size={18} color={colors.textTertiary} /></Pressable><View style={styles.divider} /><View style={styles.row}><View style={styles.icon}><Ionicons name="notifications-outline" size={19} color={colors.primary} /></View><View style={styles.flex}><Text style={styles.rowTitle}>Notification preferences</Text><Text style={styles.copy}>Manage booking and parking updates in Settings.</Text></View></View></View><Text style={styles.heading}>ACCOUNT DATA</Text><View style={styles.danger}><View style={styles.dangerTop}><View style={styles.dangerIcon}><Ionicons name="trash-outline" size={19} color={colors.error} /></View><View style={styles.flex}><Text style={styles.rowTitle}>Delete Account</Text><Text style={styles.copy}>Removes local development account data only.</Text></View></View><Pressable accessibilityRole="button" accessibilityLabel="Delete account" onPress={remove} style={({ pressed }) => [styles.delete, pressed && styles.pressed]}><Text style={styles.deleteText}>Delete Account</Text></Pressable></View></SafeAreaView>; }
const styles = StyleSheet.create({ screen: { flex: 1, padding: spacing.lg, gap: spacing.md, backgroundColor: colors.background }, title: { ...typography.title1, color: colors.textPrimary, marginBottom: spacing.md }, heading: { ...typography.captionStrong, color: colors.textTertiary, letterSpacing: 0.5, marginTop: spacing.sm }, card: { borderWidth: 1, borderColor: colors.borderSubtle, borderRadius: radius.lg, overflow: 'hidden', backgroundColor: colors.surface }, row: { minHeight: 68, flexDirection: 'row', alignItems: 'center', gap: spacing.md, paddingHorizontal: spacing.md }, icon: { width: 30, alignItems: 'center' }, flex: { flex: 1 }, rowTitle: { ...typography.bodyStrong, color: colors.textPrimary }, copy: { ...typography.caption, color: colors.textSecondary, marginTop: 2 }, divider: { height: 1, marginLeft: 62, backgroundColor: colors.borderSubtle }, danger: { gap: spacing.md, padding: spacing.md, borderWidth: 1, borderColor: colors.errorSoft, borderRadius: radius.lg, backgroundColor: colors.surface }, dangerTop: { flexDirection: 'row', alignItems: 'center', gap: spacing.md }, dangerIcon: { width: 30, height: 30, alignItems: 'center', justifyContent: 'center', borderRadius: radius.full, backgroundColor: colors.errorSoft }, delete: { minHeight: 48, alignItems: 'center', justifyContent: 'center', borderRadius: radius.md, backgroundColor: colors.errorSoft }, deleteText: { ...typography.bodyStrong, color: colors.error }, pressed: { opacity: 0.82 } });
