import { Ionicons } from '@expo/vector-icons';
import { Href, router, useFocusEffect } from 'expo-router';
import { useCallback, useState } from 'react';
import { Alert, FlatList, Pressable, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { EmptyState } from '@/components/ui/empty-state';
import { savedPlaceService } from '@/services/saved-place-service';
import { SavedPlace } from '@/types/domain';
import { colors, radius, spacing, typography } from '@/theme/tokens';

export default function SavedPlacesScreen() { const [items, setItems] = useState<SavedPlace[]>([]); const load = useCallback(() => savedPlaceService.getSavedPlaces().then(setItems), []); useFocusEffect(useCallback(() => { void load(); }, [load])); const remove = (item: SavedPlace) => Alert.alert('Remove saved place?', `${item.label} will be removed from this device.`, [{ text: 'Cancel', style: 'cancel' }, { text: 'Remove', style: 'destructive', onPress: () => void savedPlaceService.remove(item.id).then(load) }]); return <SafeAreaView style={styles.screen}><View style={styles.header}><Text style={styles.title}>Saved Places</Text><Pressable accessibilityRole="button" accessibilityLabel="Add saved place" onPress={() => router.push('/saved-place-form' as Href)} style={({ pressed }) => [styles.add, pressed && styles.pressed]}><Ionicons name="add" size={18} color={colors.primary} /><Text style={styles.addText}>Add Place</Text></Pressable></View><FlatList data={items} keyExtractor={(item) => item.id} contentContainerStyle={items.length ? styles.list : styles.empty} renderItem={({ item }) => <PlaceRow item={item} onRemove={remove} />} ListEmptyComponent={<EmptyState icon="location-outline" title="No saved places yet." description="Save locations you visit often for faster parking searches." actionLabel="Add Place" onAction={() => router.push('/saved-place-form' as Href)} />} /></SafeAreaView>; }
function PlaceRow({ item, onRemove }: { item: SavedPlace; onRemove: (item: SavedPlace) => void }) { const type = item.type ?? (item.label.toLowerCase() === 'home' ? 'home' : item.label.toLowerCase() === 'work' ? 'work' : 'custom'); const icon = type === 'home' ? 'home-outline' : type === 'work' ? 'briefcase-outline' : 'location-outline'; const typeLabel = type === 'custom' ? 'Saved place' : type[0].toUpperCase() + type.slice(1); return <View style={styles.row}><View style={styles.icon}><Ionicons name={icon} size={19} color={colors.primary} /></View><View style={styles.flex}><View style={styles.nameRow}><Text style={styles.name}>{item.label}</Text><Text style={styles.type}>{typeLabel}</Text></View><Text numberOfLines={1} style={styles.address}>{item.address}</Text></View><Pressable accessibilityRole="button" accessibilityLabel={`Edit ${item.label}`} onPress={() => router.push(`/saved-place-form?id=${item.id}` as Href)} style={styles.iconAction}><Ionicons name="create-outline" size={18} color={colors.primary} /></Pressable><Pressable accessibilityRole="button" accessibilityLabel={`Delete ${item.label}`} onPress={() => onRemove(item)} style={styles.iconAction}><Ionicons name="trash-outline" size={18} color={colors.error} /></Pressable></View>; }
const styles = StyleSheet.create({ screen: { flex: 1, padding: spacing.lg, backgroundColor: colors.background }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: spacing.lg }, title: { ...typography.title1, color: colors.textPrimary }, add: { minHeight: 40, flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: spacing.sm, borderRadius: radius.full, backgroundColor: colors.primarySoft }, addText: { ...typography.captionStrong, color: colors.primary }, list: { gap: spacing.sm }, empty: { flexGrow: 1 }, row: { minHeight: 72, flexDirection: 'row', alignItems: 'center', gap: spacing.sm, paddingHorizontal: spacing.md, borderWidth: 1, borderColor: colors.borderSubtle, borderRadius: radius.lg, backgroundColor: colors.surface }, icon: { width: 38, height: 38, justifyContent: 'center', alignItems: 'center', borderRadius: radius.md, backgroundColor: colors.primarySoft }, flex: { flex: 1 }, nameRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm }, name: { ...typography.bodyStrong, color: colors.textPrimary }, type: { ...typography.caption, color: colors.textTertiary }, address: { ...typography.caption, color: colors.textSecondary, marginTop: 2 }, iconAction: { width: 32, height: 40, alignItems: 'center', justifyContent: 'center' }, pressed: { opacity: 0.82 } });
