import { router, useLocalSearchParams } from 'expo-router';
import { useEffect, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { KeyboardSafeScrollView } from '@/components/layout/keyboard-safe-scroll-view';
import { FormTextInput } from '@/components/ui/form-text-input';
import { PrimaryButton } from '@/components/ui/primary-button';
import { savedPlaceService } from '@/services/saved-place-service';
import { SavedPlace } from '@/types/domain';
import { colors, radius, spacing, typography } from '@/theme/tokens';
export default function SavedPlaceForm() { const { id, type } = useLocalSearchParams<{ id: string; type: 'home' | 'work' | 'custom' }>(); const [current, setCurrent] = useState<SavedPlace | null>(null); const [placeType, setPlaceType] = useState<'home' | 'work' | 'custom'>(type ?? 'custom'); const [label, setLabel] = useState(type === 'home' ? 'Home' : type === 'work' ? 'Work' : ''); const [address, setAddress] = useState(''); const [error, setError] = useState(''); useEffect(() => { if (id) void savedPlaceService.getSavedPlaces().then((items) => { const item = items.find((value) => value.id === id) ?? null; setCurrent(item); if (item) { setLabel(item.label); setAddress(item.address); setPlaceType(item.type ?? (item.label.toLowerCase() === 'home' ? 'home' : item.label.toLowerCase() === 'work' ? 'work' : 'custom')); } }); }, [id]); const save = async () => { if (!label.trim() || !address.trim()) { setError('Enter a label and address.'); return; } const payload = { label: placeType === 'home' ? 'Home' : placeType === 'work' ? 'Work' : label.trim(), address: address.trim(), latitude: 0, longitude: 0, type: placeType }; if (current) await savedPlaceService.update(current.id, payload); else await savedPlaceService.save(payload); router.back(); }; return <SafeAreaView style={styles.screen}><KeyboardSafeScrollView contentContainerStyle={styles.content}><Text style={styles.title}>{current ? 'Edit Saved Place' : 'Add Saved Place'}</Text><Text style={styles.heading}>Type</Text><View style={styles.types}>{(['home', 'work', 'custom'] as const).map((item) => <Pressable key={item} accessibilityRole="radio" accessibilityState={{ selected: placeType === item }} onPress={() => { setPlaceType(item); if (item !== 'custom') setLabel(item === 'home' ? 'Home' : 'Work'); }} style={[styles.chip, placeType === item && styles.selected]}><Text style={[styles.chipText, placeType === item && styles.selectedText]}>{item[0].toUpperCase() + item.slice(1)}</Text></Pressable>)}</View><FormTextInput label="Label" value={label} onChangeText={setLabel} placeholder="Gym, Home or Work" error={error} /><FormTextInput label="Location / address" value={address} onChangeText={setAddress} placeholder="Anna Nagar, Chennai" multiline style={styles.addressInput} /><PrimaryButton label="Save Place" onPress={() => void save()} /></KeyboardSafeScrollView></SafeAreaView>; }
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.background }, content: { padding: spacing.lg, gap: spacing.lg, paddingBottom: spacing.xxxl }, title: { ...typography.title1, color: colors.textPrimary }, heading: { ...typography.bodyStrong, color: colors.textPrimary }, types: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }, chip: { minHeight: 42, justifyContent: 'center', paddingHorizontal: spacing.md, borderWidth: 1, borderColor: colors.border, borderRadius: radius.full, backgroundColor: colors.surface }, selected: { borderColor: colors.primary, backgroundColor: colors.primarySoft }, chipText: { ...typography.bodySmall, color: colors.textSecondary }, selectedText: { color: colors.primary }, addressInput: { minHeight: 104, textAlignVertical: 'top', paddingTop: spacing.md } });
