import { Ionicons } from '@expo/vector-icons';
import { Href, router } from 'expo-router';
import { useEffect, useState } from 'react';
import { FlatList, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { mockSearchLocations } from '@/mock/locations';
import { searchService } from '@/services/search-service';
import { useAppStore } from '@/store/app-store';
import { SearchLocation } from '@/types/domain';
import { colors, radius, shadows, spacing, typography } from '@/theme/tokens';

export default function SearchScreen() {
  const [query, setQuery] = useState('');
  const [results, setResults] = useState<SearchLocation[]>(mockSearchLocations);
  const [recent, setRecent] = useState<SearchLocation[]>([]);
  const setDestination = useAppStore((state) => state.setDestination);
  useEffect(() => { let isActive = true; void searchService.getRecentSearches().then((savedSearches) => { if (isActive) setRecent(savedSearches); }); return () => { isActive = false; }; }, []);
  useEffect(() => { let isActive = true; void searchService.searchLocations(query).then((nextResults) => { if (isActive) setResults(nextResults); }); return () => { isActive = false; }; }, [query]);
  const select = async (location: SearchLocation) => { await searchService.addRecentSearch(location); setDestination(location); router.replace('/results' as Href); };
  const clearRecent = async () => { await searchService.clearRecentSearches(); setRecent([]); };
  const data = query ? results : recent.length ? recent : mockSearchLocations;
  const title = query ? `${results.length} matching locations` : recent.length ? 'Recent searches' : 'Popular destinations';
  return <SafeAreaView style={styles.screen} edges={['top']}><View style={styles.header}><Pressable accessibilityRole="button" accessibilityLabel="Back" onPress={() => router.back()} style={styles.back}><Ionicons name="arrow-back" size={20} color={colors.textPrimary} /></Pressable><View style={styles.inputShell}><Ionicons name="search-outline" size={20} color={colors.textSecondary} /><TextInput autoFocus value={query} onChangeText={setQuery} placeholder="Search area or destination" placeholderTextColor={colors.textTertiary} style={styles.input} returnKeyType="search" />{query ? <Pressable accessibilityRole="button" accessibilityLabel="Clear search" onPress={() => setQuery('')}><Ionicons name="close-circle" size={20} color={colors.textTertiary} /></Pressable> : null}</View></View><View style={styles.titleRow}><Text style={styles.title}>{title}</Text>{!query && recent.length ? <Pressable accessibilityRole="button" onPress={() => void clearRecent()}><Text style={styles.clear}>Clear</Text></Pressable> : null}</View><FlatList data={data} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} keyboardShouldPersistTaps="handled" renderItem={({ item }) => <Pressable accessibilityRole="button" accessibilityLabel={`Choose ${item.name}`} onPress={() => void select(item)} style={({ pressed }) => [styles.row, pressed && styles.pressed]}><View style={styles.rowIcon}><Ionicons name={item.category === 'recent' ? 'time-outline' : 'location-outline'} size={20} color={colors.primary} /></View><View style={styles.rowCopy}><Text style={styles.rowTitle}>{item.name}</Text><Text style={styles.rowSubtitle}>{item.subtitle}</Text></View><Ionicons name="arrow-forward" size={18} color={colors.textTertiary} /></Pressable>} ListEmptyComponent={<View style={styles.empty}><Ionicons name="search-outline" size={30} color={colors.textTertiary} /><Text style={styles.emptyTitle}>No places found</Text><Text style={styles.emptyText}>Try a landmark, neighbourhood or parking facility.</Text></View>} /></SafeAreaView>;
}
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.background }, header: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, padding: spacing.lg }, back: { width: 42, height: 42, alignItems: 'center', justifyContent: 'center', borderRadius: radius.full, backgroundColor: colors.surface }, inputShell: { minHeight: 52, flex: 1, flexDirection: 'row', alignItems: 'center', gap: spacing.sm, paddingHorizontal: spacing.md, borderRadius: radius.md, backgroundColor: colors.surface, ...shadows.card }, input: { ...typography.body, flex: 1, color: colors.textPrimary }, titleRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: spacing.lg, paddingBottom: spacing.sm }, title: { ...typography.title3, color: colors.textPrimary }, clear: { ...typography.bodySmall, color: colors.primary, fontWeight: '700' }, list: { padding: spacing.lg, paddingTop: spacing.sm, gap: spacing.sm }, row: { minHeight: 72, flexDirection: 'row', alignItems: 'center', gap: spacing.md, padding: spacing.md, borderRadius: radius.lg, backgroundColor: colors.surface }, pressed: { opacity: 0.72 }, rowIcon: { width: 42, height: 42, alignItems: 'center', justifyContent: 'center', borderRadius: radius.md, backgroundColor: colors.primarySoft }, rowCopy: { flex: 1 }, rowTitle: { ...typography.bodyStrong, color: colors.textPrimary }, rowSubtitle: { ...typography.bodySmall, color: colors.textSecondary, marginTop: 2 }, empty: { alignItems: 'center', paddingTop: 80, paddingHorizontal: spacing.xxxl }, emptyTitle: { ...typography.title3, color: colors.textPrimary, marginTop: spacing.md }, emptyText: { ...typography.bodySmall, color: colors.textSecondary, textAlign: 'center', marginTop: spacing.sm } });
