import { Href, router, useFocusEffect, useLocalSearchParams } from 'expo-router';
import { useCallback, useState } from 'react';
import { ActivityIndicator, FlatList, Pressable, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { EmptyState } from '@/components/ui/empty-state';
import { supportService } from '@/services/support-service';
import { SupportTicket } from '@/types/domain';
import { formatBookingDateTime } from '@/utils/booking-time';
import { colors, radius, spacing, typography } from '@/theme/tokens';
export default function SupportRequestsScreen() { const { id } = useLocalSearchParams<{ id: string }>(); const [items, setItems] = useState<SupportTicket[]>([]); const [loading, setLoading] = useState(true); const load = useCallback(async () => { setLoading(true); setItems(await supportService.getTickets()); setLoading(false); }, []); useFocusEffect(useCallback(() => { void load(); }, [load])); const ticket = id ? items.find((item) => item.id === id) : null; if (loading) return <SafeAreaView style={styles.center}><ActivityIndicator color={colors.primary} /></SafeAreaView>; if (id) return <SafeAreaView style={styles.screen}>{ticket ? <View style={styles.detail}><View style={styles.detailTop}><View><Text style={styles.ref}>{ticket.reference}</Text><Text style={styles.date}>{formatBookingDateTime(ticket.createdAt)}</Text></View><Status status={ticket.status} /></View><Row label="Category" value={ticket.category} />{ticket.bookingId ? <Row label="Related booking" value={ticket.bookingId} /> : null}<Row label="Subject" value={ticket.subject} /><View style={styles.description}><Text style={styles.label}>Description</Text><Text style={styles.body}>{ticket.description}</Text></View></View> : <EmptyState icon="alert-circle-outline" title="Support request not found." description="This request may no longer be available." actionLabel="Back to requests" onAction={() => router.replace('/support-requests' as Href)} />}</SafeAreaView>; return <SafeAreaView style={styles.screen}><Text style={styles.title}>My Support Requests</Text><FlatList data={items} keyExtractor={(item) => item.id} contentContainerStyle={items.length ? styles.list : styles.empty} renderItem={({ item }) => <Pressable accessibilityRole="button" onPress={() => router.push(`/support-requests?id=${item.id}` as Href)} style={({ pressed }) => [styles.card, pressed && styles.pressed]}><View style={styles.ticketTop}><Text style={styles.ref}>{item.reference}</Text><Status status={item.status} /></View><Text style={styles.subject}>{item.subject}</Text><Text style={styles.body}>{item.category}{item.bookingId ? ' · Related booking' : ''}</Text><Text style={styles.date}>{formatBookingDateTime(item.createdAt)}</Text></Pressable>} ListEmptyComponent={<EmptyState icon="chatbubble-outline" title="No support requests yet." description="Create a request if you need help with ParkEase." actionLabel="Create Support Request" onAction={() => router.push('/support-request' as Href)} />} /></SafeAreaView>; }
function Status({ status }: { status: string }) { return <View style={styles.status}><Text style={styles.statusText}>{status}</Text></View>; }
function Row({ label, value }: { label: string; value: string }) { return <View style={styles.row}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value}</Text></View>; }
const styles = StyleSheet.create({ screen: { flex: 1, padding: spacing.lg, backgroundColor: colors.background }, center: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: colors.background }, title: { ...typography.title1, color: colors.textPrimary, marginBottom: spacing.lg }, list: { gap: spacing.sm, paddingBottom: spacing.xxxl }, empty: { flexGrow: 1 }, card: { gap: spacing.xs, padding: spacing.md, borderWidth: 1, borderColor: colors.borderSubtle, borderRadius: radius.lg, backgroundColor: colors.surface }, ticketTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, ref: { ...typography.bodyStrong, color: colors.primary }, status: { paddingHorizontal: spacing.sm, paddingVertical: 4, borderRadius: radius.full, backgroundColor: colors.primarySoft }, statusText: { ...typography.captionStrong, color: colors.primary, textTransform: 'capitalize' }, subject: { ...typography.bodyStrong, color: colors.textPrimary, marginTop: spacing.xs }, body: { ...typography.bodySmall, color: colors.textSecondary }, date: { ...typography.caption, color: colors.textTertiary, marginTop: spacing.xs }, detail: { gap: spacing.md }, detailTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' }, row: { gap: 2, padding: spacing.md, borderWidth: 1, borderColor: colors.borderSubtle, borderRadius: radius.md, backgroundColor: colors.surface }, label: { ...typography.captionStrong, color: colors.textTertiary }, value: { ...typography.body, color: colors.textPrimary }, description: { gap: spacing.sm, padding: spacing.md, borderWidth: 1, borderColor: colors.borderSubtle, borderRadius: radius.md, backgroundColor: colors.surface }, pressed: { opacity: 0.82 } });
