import { router } from 'expo-router';
import { useEffect, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { KeyboardSafeScrollView } from '@/components/layout/keyboard-safe-scroll-view';
import { FormTextInput } from '@/components/ui/form-text-input';
import { PrimaryButton } from '@/components/ui/primary-button';
import { bookingService } from '@/services/booking-service';
import { supportService } from '@/services/support-service';
import { Booking, SupportTicket } from '@/types/domain';
import { colors, radius, spacing, typography } from '@/theme/tokens';

const categories: { id: SupportTicket['category']; label: string }[] = [{ id: 'booking', label: 'Booking' }, { id: 'payment', label: 'Payment' }, { id: 'refund', label: 'Refund' }, { id: 'parking', label: 'Parking' }, { id: 'vehicle', label: 'Vehicle' }, { id: 'account', label: 'Account' }, { id: 'other', label: 'Other' }];
export default function SupportRequestScreen() {
  const [category, setCategory] = useState<SupportTicket['category']>('booking'); const [bookings, setBookings] = useState<Booking[]>([]); const [bookingId, setBookingId] = useState<string | undefined>(); const [subject, setSubject] = useState(''); const [description, setDescription] = useState(''); const [error, setError] = useState(''); const [success, setSuccess] = useState<SupportTicket | null>(null); const [submitting, setSubmitting] = useState(false);
  useEffect(() => { let mounted = true; void bookingService.getBookings().then((items) => { if (mounted) setBookings(items); }); return () => { mounted = false; }; }, []);
  const submit = async () => { if (submitting) return; setSubmitting(true); setError(''); try { setSuccess(await supportService.createTicket({ category, bookingId, subject, description })); } catch { setError('Add a subject and description.'); } finally { setSubmitting(false); } };
  if (success) return <SafeAreaView style={styles.screen}><View style={styles.success}><View style={styles.successMark}><Text style={styles.successMarkText}>✓</Text></View><Text style={styles.title}>Support request submitted</Text><Text style={styles.successText}>Your support reference</Text><Text style={styles.ref}>{success.reference}</Text><PrimaryButton label="View Request" onPress={() => router.replace(`/support-requests?id=${success.id}` as never)} /><PrimaryButton label="Back to Support" variant="secondary" onPress={() => router.replace('/help' as never)} /></View></SafeAreaView>;
  return <SafeAreaView style={styles.screen}><KeyboardSafeScrollView contentContainerStyle={styles.content}><Text style={styles.title}>Report a Problem</Text><Text style={styles.intro}>Tell us what happened and we’ll save a support request for you.</Text><Text style={styles.label}>Category</Text><View style={styles.chips}>{categories.map((item) => <Pressable key={item.id} accessibilityRole="radio" accessibilityLabel={`${item.label} category`} accessibilityState={{ selected: category === item.id }} onPress={() => setCategory(item.id)} style={[styles.chip, category === item.id && styles.selected]}><Text style={[styles.chipText, category === item.id && styles.selectedText]}>{item.label}</Text></Pressable>)}</View>{(['booking', 'payment', 'refund'] as string[]).includes(category) && <View><Text style={styles.label}>Related booking <Text style={styles.optional}>(optional)</Text></Text>{bookings.map((item) => <Pressable key={item.id} accessibilityRole="radio" accessibilityLabel={`${item.bookingReference}, ${item.parkingName}`} accessibilityState={{ selected: bookingId === item.id }} onPress={() => setBookingId(item.id)} style={[styles.booking, bookingId === item.id && styles.bookingSelected]}><Text numberOfLines={1} style={styles.bookingText}>{item.bookingReference} · {item.parkingName}</Text></Pressable>)}</View>}<FormTextInput label="Subject" value={subject} onChangeText={setSubject} placeholder="What can we help with?" error={error} /><FormTextInput label="Description" value={description} onChangeText={setDescription} placeholder="Describe the issue" multiline style={styles.descriptionInput} /><PrimaryButton label="Submit Request" isLoading={submitting} onPress={() => void submit()} /></KeyboardSafeScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.background }, content: { padding: spacing.lg, gap: spacing.lg, paddingBottom: spacing.xxxl }, success: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: spacing.lg, gap: spacing.md }, successMark: { width: 54, height: 54, alignItems: 'center', justifyContent: 'center', borderRadius: radius.full, backgroundColor: colors.successSoft }, successMarkText: { ...typography.title2, color: colors.success }, title: { ...typography.title1, color: colors.textPrimary }, intro: { ...typography.bodySmall, color: colors.textSecondary, marginTop: -spacing.sm }, successText: { ...typography.bodySmall, color: colors.textSecondary }, ref: { ...typography.title2, color: colors.primary }, label: { ...typography.bodyStrong, color: colors.textPrimary }, optional: { ...typography.bodySmall, color: colors.textSecondary }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm, marginTop: -spacing.sm }, chip: { paddingHorizontal: spacing.md, paddingVertical: spacing.sm, borderWidth: 1, borderColor: colors.border, borderRadius: radius.full, backgroundColor: colors.surface }, selected: { borderColor: colors.primary, backgroundColor: colors.primarySoft }, chipText: { ...typography.captionStrong, color: colors.textSecondary }, selectedText: { color: colors.primary }, booking: { minHeight: 44, justifyContent: 'center', paddingHorizontal: spacing.md, borderWidth: 1, borderColor: colors.borderSubtle, borderRadius: radius.md, backgroundColor: colors.surface, marginTop: spacing.sm }, bookingSelected: { borderColor: colors.primary, backgroundColor: colors.primarySoft }, bookingText: { ...typography.bodySmall, color: colors.textPrimary }, descriptionInput: { minHeight: 116, textAlignVertical: 'top', paddingTop: spacing.md } });
