import { Ionicons } from '@expo/vector-icons';
import { Href, router, useLocalSearchParams } from 'expo-router';
import { useEffect, useState } from 'react';
import { Alert, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { FormTextInput } from '@/components/ui/form-text-input';
import { PrimaryButton } from '@/components/ui/primary-button';
import { vehicleService } from '@/services/vehicle-service';
import { useAppStore } from '@/store/app-store';
import { VehicleType } from '@/types/domain';
import { colors, radius, spacing, typography } from '@/theme/tokens';

const types: { value: VehicleType; label: string; icon: keyof typeof Ionicons.glyphMap }[] = [{ value: 'car', label: 'Car', icon: 'car-outline' }, { value: 'suv', label: 'SUV', icon: 'car-sport-outline' }, { value: 'motorcycle', label: 'Motorcycle', icon: 'bicycle-outline' }];
const colorsList = ['White', 'Black', 'Silver', 'Grey', 'Blue', 'Red', 'Other'];
const normalizeRegistration = (value: string) => value.toUpperCase().replace(/[^A-Z0-9 ]/g, '').replace(/\s+/g, ' ').trim();
const validRegistration = (value: string) => /^[A-Z]{2}\s?\d{1,2}\s?[A-Z]{1,3}\s?\d{3,4}$/.test(value.replace(/\s/g, ''));
export default function VehicleFormScreen() {
  const { id, returnTo = 'vehicles' } = useLocalSearchParams<{ id?: string; returnTo?: string }>();
  const [type, setType] = useState<VehicleType>('car'); const [registrationNumber, setRegistrationNumber] = useState(''); const [brand, setBrand] = useState(''); const [model, setModel] = useState(''); const [color, setColor] = useState('White'); const [isDefault, setIsDefault] = useState(false); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { if (!id) return; void vehicleService.getVehicleById(id).then((vehicle) => { if (vehicle) { setType(vehicle.type); setRegistrationNumber(vehicle.registrationNumber); setBrand(vehicle.brand); setModel(vehicle.model); setColor(vehicle.color); setIsDefault(vehicle.isDefault); } }); }, [id]);
  const finishPath = returnTo === 'booking' ? '/booking-setup' : '/vehicles';
  const save = async () => { if (!validRegistration(registrationNumber) || !brand.trim() || !model.trim()) { setError('Enter a valid vehicle registration number, brand and model.'); return; } setSaving(true); const input = { type, registrationNumber: normalizeRegistration(registrationNumber), brand: brand.trim(), model: model.trim(), color, isDefault }; if (id) await vehicleService.updateVehicle(id, input); else { const vehicle = await vehicleService.addVehicle(input); if (returnTo === 'booking') useAppStore.getState().updateBookingDraft({ vehicleId: vehicle.id }); } setSaving(false); router.replace(finishPath as Href); };
  const remove = () => Alert.alert('Remove this vehicle?', 'You can add it again later.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Remove', style: 'destructive', onPress: () => { if (id) void vehicleService.deleteVehicle(id).then(() => router.replace(finishPath as Href)); } }]);
  return <SafeAreaView style={styles.screen} edges={['top']}><KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} style={styles.flex}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><View style={styles.header}><Pressable accessibilityRole="button" accessibilityLabel="Back" onPress={() => router.back()} style={styles.back}><Ionicons name="arrow-back" size={20} color={colors.textPrimary} /></Pressable><Text style={styles.title}>{id ? 'Edit vehicle' : 'Add vehicle'}</Text></View><Text style={styles.label}>Vehicle type</Text><View style={styles.typeRow}>{types.map((option) => <Pressable key={option.value} accessibilityRole="radio" accessibilityState={{ selected: type === option.value }} onPress={() => setType(option.value)} style={[styles.type, type === option.value && styles.typeSelected]}><Ionicons name={option.icon} size={22} color={type === option.value ? colors.primary : colors.textSecondary} /><Text style={[styles.typeText, type === option.value && styles.typeTextSelected]}>{option.label}</Text></Pressable>)}</View><View style={styles.form}><FormTextInput label="Registration number" value={registrationNumber} onChangeText={(value) => { setRegistrationNumber(normalizeRegistration(value)); setError(''); }} placeholder="TN 01 AB 1234" autoCapitalize="characters" maxLength={13} /><FormTextInput label="Brand" value={brand} onChangeText={setBrand} placeholder="e.g. Hyundai" /><FormTextInput label="Model" value={model} onChangeText={setModel} placeholder="e.g. i20" /><Text style={styles.label}>Color</Text><View style={styles.colorRow}>{colorsList.map((value) => <Pressable key={value} accessibilityRole="radio" accessibilityState={{ selected: color === value }} onPress={() => setColor(value)} style={[styles.color, color === value && styles.colorSelected]}><Text style={[styles.colorText, color === value && styles.colorTextSelected]}>{value}</Text></Pressable>)}</View><Pressable accessibilityRole="checkbox" accessibilityState={{ checked: isDefault }} onPress={() => setIsDefault((value) => !value)} style={styles.defaultRow}><Ionicons name={isDefault ? 'checkbox' : 'square-outline'} size={22} color={colors.primary} /><View><Text style={styles.defaultTitle}>Set as default vehicle</Text><Text style={styles.defaultText}>Used automatically for your next reservation.</Text></View></Pressable>{error ? <Text style={styles.error}>{error}</Text> : null}<PrimaryButton label={id ? 'Save changes' : 'Save vehicle'} icon="checkmark" isLoading={saving} onPress={() => void save()} />{id ? <Pressable accessibilityRole="button" onPress={remove} style={styles.remove}><Text style={styles.removeText}>Remove vehicle</Text></Pressable> : null}</View></ScrollView></KeyboardAvoidingView></SafeAreaView>;
}
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.background }, flex: { flex: 1 }, content: { padding: spacing.lg, paddingBottom: spacing.xxxl }, header: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, marginBottom: spacing.xl }, back: { width: 42, height: 42, alignItems: 'center', justifyContent: 'center', borderRadius: radius.full, backgroundColor: colors.surface }, title: { ...typography.title2, color: colors.textPrimary }, label: { ...typography.bodyStrong, color: colors.textPrimary, marginBottom: spacing.sm }, typeRow: { flexDirection: 'row', gap: spacing.sm }, type: { flex: 1, minHeight: 82, alignItems: 'center', justifyContent: 'center', gap: spacing.xs, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, backgroundColor: colors.surface }, typeSelected: { borderColor: colors.primary, backgroundColor: colors.primarySoft }, typeText: { ...typography.captionStrong, color: colors.textSecondary }, typeTextSelected: { color: colors.primary }, form: { gap: spacing.lg, marginTop: spacing.xl }, colorRow: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }, color: { paddingHorizontal: spacing.md, paddingVertical: spacing.sm, borderWidth: 1, borderColor: colors.border, borderRadius: radius.full, backgroundColor: colors.surface }, colorSelected: { borderColor: colors.primary, backgroundColor: colors.primarySoft }, colorText: { ...typography.captionStrong, color: colors.textSecondary }, colorTextSelected: { color: colors.primary }, defaultRow: { flexDirection: 'row', gap: spacing.sm, alignItems: 'center', padding: spacing.md, borderRadius: radius.md, backgroundColor: colors.surfaceMuted }, defaultTitle: { ...typography.bodyStrong, color: colors.textPrimary }, defaultText: { ...typography.caption, color: colors.textSecondary, marginTop: 2 }, error: { ...typography.bodySmall, color: colors.error, marginTop: -spacing.sm }, remove: { alignItems: 'center', padding: spacing.sm }, removeText: { ...typography.bodyStrong, color: colors.error } });
