import { Href, router } from 'expo-router';
import { useEffect, useState } from 'react';
import { Alert, FlatList, Pressable, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { VehicleCard } from '@/components/booking/vehicle-card';
import { EmptyState } from '@/components/ui/empty-state';
import { PrimaryButton } from '@/components/ui/primary-button';
import { vehicleService } from '@/services/vehicle-service';
import { Vehicle } from '@/types/domain';
import { colors, radius, spacing, typography } from '@/theme/tokens';

export default function VehiclesScreen() { const [vehicles, setVehicles] = useState<Vehicle[]>([]); useEffect(() => { void vehicleService.getVehicles().then(setVehicles); }, []); const remove = (vehicle: Vehicle) => Alert.alert('Remove this vehicle?', 'You can add it again later.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Remove', style: 'destructive', onPress: () => { void vehicleService.deleteVehicle(vehicle.id).then(setVehicles); } }]); return <SafeAreaView style={styles.screen} edges={['top']}><View style={styles.header}><Pressable accessibilityRole="button" accessibilityLabel="Back" onPress={() => router.back()} style={styles.back}><Text>←</Text></Pressable><Text style={styles.title}>My vehicles</Text></View>{vehicles.length ? <FlatList data={vehicles} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} renderItem={({ item }) => <View style={styles.item}><VehicleCard vehicle={item} onEdit={() => router.push(`/vehicle-form?id=${item.id}` as Href)} /><Pressable accessibilityRole="button" onPress={() => void vehicleService.setDefaultVehicle(item.id).then(setVehicles)} style={styles.default}><Text style={styles.defaultText}>{item.isDefault ? 'Default vehicle' : 'Make default'}</Text></Pressable><Pressable accessibilityRole="button" onPress={() => remove(item)} style={styles.remove}><Text style={styles.removeText}>Remove</Text></Pressable></View>} ListFooterComponent={<PrimaryButton label="Add vehicle" icon="add-circle-outline" onPress={() => router.push('/vehicle-form' as Href)} />} /> : <EmptyState icon="car-outline" title="No vehicles added yet" description="Add a vehicle for faster parking reservations." actionLabel="Add your first vehicle" onAction={() => router.push('/vehicle-form' as Href)} />}</SafeAreaView>; }
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.background }, header: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, padding: spacing.lg }, back: { width: 42, height: 42, alignItems: 'center', justifyContent: 'center', borderRadius: radius.full, backgroundColor: colors.surface }, title: { ...typography.title2, color: colors.textPrimary }, list: { gap: spacing.sm, padding: spacing.lg, paddingTop: 0 }, item: { position: 'relative' }, default: { alignSelf: 'flex-end', marginTop: spacing.xs, marginRight: spacing.xs, padding: spacing.xs }, defaultText: { ...typography.captionStrong, color: colors.primary }, remove: { position: 'absolute', right: 44, bottom: 0, padding: spacing.xs }, removeText: { ...typography.captionStrong, color: colors.error } });
