import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { AuthScreen } from '@/components/layout/auth-screen';
import { PrimaryButton } from '@/components/ui/primary-button';
import { locationService } from '@/services/location-service';
import { useAppStore } from '@/store/app-store';
import { colors, radius, spacing, typography } from '@/theme/tokens';

export default function LocationPermissionScreen() {
  const [isRequesting, setIsRequesting] = useState(false);
  const [message, setMessage] = useState('');
  const { setLocationPermission, completeLocationIntro } = useAppStore();
  const continueToApp = async () => { await completeLocationIntro(); router.replace('/'); };
  const allow = async () => { setIsRequesting(true); setMessage(''); const status = await locationService.requestPermission(); setLocationPermission(status); setIsRequesting(false); if (status === 'granted') { await continueToApp(); return; } setMessage(status === 'unavailable' ? "We couldn't access your location. You can enable it later from Settings." : 'Nearby results may be limited without location access. You can enable it later from Settings.'); };
  return <AuthScreen><View style={styles.content}><View style={styles.intro}><View style={styles.illustration}><View style={styles.ringOne} /><View style={styles.ringTwo} /><View style={styles.icon}><Ionicons name="location" size={42} color={colors.primary} /></View></View><Text style={styles.title}>Find parking near you</Text><Text style={styles.description}>Allow location access so ParkEase can show nearby parking spaces and calculate accurate distance.</Text><View style={styles.benefits}><Benefit icon="car-outline" text="Discover nearby parking" /><Benefit icon="walk-outline" text="See accurate distance" /><Benefit icon="navigate-outline" text="Navigate easily" /></View></View><View style={styles.actions}><PrimaryButton label="Allow Location" icon="location-outline" isLoading={isRequesting} onPress={() => void allow()} />{message ? <Text accessibilityLiveRegion="polite" style={styles.message}>{message}</Text> : null}{message ? <Pressable accessibilityRole="button" onPress={() => void locationService.openSettings()}><Text style={styles.settings}>Open Settings</Text></Pressable> : null}<Pressable accessibilityRole="button" onPress={() => void continueToApp()}><Text style={styles.notNow}>Not now</Text></Pressable></View></View></AuthScreen>;
}
function Benefit({ icon, text }: { icon: keyof typeof Ionicons.glyphMap; text: string }) { return <View style={styles.benefit}><Ionicons name={icon} size={19} color={colors.primary} /><Text style={styles.benefitText}>{text}</Text></View>; }
const styles = StyleSheet.create({ content: { flex: 1, justifyContent: 'space-between', paddingVertical: spacing.xl }, intro: { alignItems: 'center', marginTop: spacing.xxl }, illustration: { width: 192, height: 192, alignItems: 'center', justifyContent: 'center', marginBottom: spacing.xxxl }, ringOne: { position: 'absolute', width: 146, height: 146, borderRadius: radius.full, backgroundColor: colors.primarySoft }, ringTwo: { position: 'absolute', width: 192, height: 192, borderRadius: radius.full, borderWidth: 1, borderColor: colors.border }, icon: { width: 74, height: 74, alignItems: 'center', justifyContent: 'center', borderRadius: radius.full, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border }, title: { ...typography.title1, color: colors.textPrimary, textAlign: 'center' }, description: { ...typography.body, color: colors.textSecondary, textAlign: 'center', marginTop: spacing.md, maxWidth: 330 }, benefits: { alignSelf: 'stretch', gap: spacing.md, marginTop: spacing.xxl }, benefit: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, padding: spacing.md, borderRadius: radius.md, backgroundColor: colors.surface }, benefitText: { ...typography.bodySmall, color: colors.textPrimary, fontWeight: '600' }, actions: { gap: spacing.md }, message: { ...typography.bodySmall, color: colors.textSecondary, textAlign: 'center' }, settings: { ...typography.bodyStrong, color: colors.primary, textAlign: 'center' }, notNow: { ...typography.bodyStrong, color: colors.textSecondary, textAlign: 'center', paddingVertical: spacing.sm } });
