import { Href, router } from 'expo-router';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { AuthScreen } from '@/components/layout/auth-screen';
import { AppLogo } from '@/components/brand/app-logo';
import { PrimaryButton } from '@/components/ui/primary-button';
import { colors, spacing, typography } from '@/theme/tokens';

export default function WelcomeScreen() { return <AuthScreen><View style={styles.content}><View style={styles.top}><AppLogo size={74} /><Text style={styles.brand}>ParkEase</Text></View><View style={styles.copy}><Text style={styles.title}>Parking made simple.</Text><Text style={styles.description}>Find, reserve and manage parking from one place.</Text></View><View style={styles.footer}><PrimaryButton label="Continue with Mobile Number" icon="phone-portrait-outline" onPress={() => router.push('/login' as Href)} /><Text style={styles.legal}>By continuing, you agree to our <Text style={styles.link}>Terms of Service</Text> and <Text style={styles.link}>Privacy Policy</Text>.</Text><Pressable accessibilityRole="button" onPress={() => router.push('/login' as Href)}><Text style={styles.login}>Already have an account? <Text style={styles.loginLink}>Log in</Text></Text></Pressable></View></View></AuthScreen>; }
const styles = StyleSheet.create({ content: { flex: 1, justifyContent: 'space-between', paddingVertical: spacing.xl }, top: { alignItems: 'center', gap: spacing.md, marginTop: spacing.xxxl }, brand: { ...typography.title2, color: colors.textPrimary }, copy: { gap: spacing.md }, title: { ...typography.display, color: colors.textPrimary }, description: { ...typography.body, color: colors.textSecondary, maxWidth: 290 }, footer: { gap: spacing.lg }, legal: { ...typography.caption, color: colors.textTertiary, textAlign: 'center', lineHeight: 18 }, link: { color: colors.textSecondary, fontWeight: '700' }, login: { ...typography.bodySmall, color: colors.textSecondary, textAlign: 'center' }, loginLink: { color: colors.primary, fontWeight: '700' } });
