import { Href, router } from 'expo-router';
import { useEffect, useState } from 'react';
import { FlatList, Pressable, StyleSheet, Text, View } from 'react-native';
import { AppHeader } from '@/components/layout/app-header';
import { EmptyState } from '@/components/ui/empty-state';
import { bookingService } from '@/services/booking-service';
import { Booking } from '@/types/domain';
import { formatRemainingTime, getBookingTemporalStatus, getRemainingMinutes } from '@/utils/booking-lifecycle';
import { colors, radius, shadows, spacing, typography } from '@/theme/tokens';

export default function ActivityScreen() { const [bookings, setBookings] = useState<Booking[]>([]); useEffect(() => { void Promise.all([bookingService.getActiveBookings(), bookingService.getUpcomingBookings()]).then(([active, upcoming]) => setBookings([...active, ...upcoming])); }, []); return <View style={styles.screen}><AppHeader eyebrow="Live status" title="Parking" />{bookings.length ? <FlatList data={bookings} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} renderItem={({ item }) => { const status = getBookingTemporalStatus(item); return <Pressable accessibilityRole="button" onPress={() => router.push(`/active-parking?id=${item.id}` as Href)} style={styles.card}><View style={styles.cardTop}><Text style={styles.status}>{status === 'upcoming' ? 'STARTS SOON' : status === 'expired' ? 'ENDED' : 'ACTIVE'}</Text><Text style={styles.remaining}>{status === 'upcoming' ? 'View details' : formatRemainingTime(getRemainingMinutes(item))}</Text></View><Text style={styles.name}>{item.parkingName}</Text><Text style={styles.meta}>{item.vehicleRegistration} · {item.slotPreference === 'any' ? 'Slot on arrival' : item.slotId?.split('-').at(-1)}</Text></Pressable>; }} /> : <EmptyState icon="car-sport-outline" title="No parking activity yet" description="Your current and upcoming parking sessions will appear here." actionLabel="Find parking" onAction={() => router.push('/results' as Href)} />}</View>; }
const styles = StyleSheet.create({ screen: { flex: 1, paddingHorizontal: spacing.lg, backgroundColor: colors.background }, list: { gap: spacing.md, paddingBottom: spacing.xxxl }, card: { padding: spacing.lg, borderRadius: radius.lg, backgroundColor: colors.surface, ...shadows.card }, cardTop: { flexDirection: 'row', justifyContent: 'space-between' }, status: { ...typography.captionStrong, color: colors.primary, letterSpacing: 0.6 }, remaining: { ...typography.captionStrong, color: colors.textSecondary }, name: { ...typography.title3, color: colors.textPrimary, marginTop: spacing.sm }, meta: { ...typography.bodySmall, color: colors.textSecondary, marginTop: spacing.xs } });
