import { Ionicons } from '@expo/vector-icons';
import { Href, router, useFocusEffect } from 'expo-router';
import { useCallback, useMemo, useState } from 'react';
import { ActivityIndicator, FlatList, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { AppHeader } from '@/components/layout/app-header';
import { BookingCard } from '@/components/booking/booking-card';
import { EmptyState } from '@/components/ui/empty-state';
import { bookingService } from '@/services/booking-service';
import { openParkingDirections } from '@/utils/directions';
import { categorizeBooking } from '@/utils/booking-history';
import { Booking, BookingCategory } from '@/types/domain';
import { mockParkingFacilities } from '@/mock/parking';
import { useAppStore } from '@/store/app-store';
import { colors, radius, spacing, typography } from '@/theme/tokens';

const tabs: BookingCategory[] = ['upcoming', 'active', 'completed', 'cancelled'];
const tabLabels: Record<BookingCategory, string> = { upcoming: 'Upcoming', active: 'Active', completed: 'Completed', cancelled: 'Cancelled' };
const emptyCopy: Record<BookingCategory, [string, string]> = { upcoming: ['No upcoming bookings.', 'Your future parking reservations will appear here.'], active: ['No active parking right now.', 'Your active parking sessions will appear here.'], completed: ['No completed bookings yet.', 'Past parking sessions will appear here.'], cancelled: ['No cancelled bookings.', 'Cancelled reservations will remain here for your records.'] };

export default function BookingsScreen() {
  const [bookings, setBookings] = useState<Booking[]>([]); const [selected, setSelected] = useState<BookingCategory>('upcoming'); const [query, setQuery] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState(false); const { updateBookingDraft } = useAppStore();
  const load = useCallback(async () => { setLoading(true); setError(false); try { const saved = await bookingService.getBookings(); setBookings(saved); const hasActive = saved.some((booking) => categorizeBooking(booking) === 'active'); setSelected((current) => current === 'upcoming' && hasActive ? 'active' : current); } catch { setError(true); } finally { setLoading(false); } }, []);
  useFocusEffect(useCallback(() => { void load(); }, [load]));
  const visibleBookings = useMemo(() => bookings.filter((booking) => categorizeBooking(booking) === selected).filter((booking) => `${booking.parkingName} ${booking.bookingReference} ${booking.vehicleRegistration}`.toLowerCase().includes(query.trim().toLowerCase())).sort((first, second) => selected === 'upcoming' ? new Date(first.entryTime).getTime() - new Date(second.entryTime).getTime() : new Date(second.exitTime).getTime() - new Date(first.exitTime).getTime()), [bookings, query, selected]);
  const bookAgain = async (id: string) => { try { updateBookingDraft(await bookingService.createBookingFromPrevious(id)); router.push('/booking-setup' as Href); } catch { router.push('/results' as Href); } };
  return <View style={styles.screen}><AppHeader eyebrow="Reservations" title="My Bookings" /><View style={styles.search}><Ionicons name="search-outline" size={19} color={colors.textTertiary} /><TextInput accessibilityLabel="Search bookings" value={query} onChangeText={setQuery} placeholder="Search parking, reference or vehicle" placeholderTextColor={colors.textTertiary} style={styles.searchInput} /></View><View style={styles.tabs}>{tabs.map((tab) => <Pressable key={tab} accessibilityRole="tab" accessibilityLabel={`${tabLabels[tab]} bookings`} accessibilityState={{ selected: selected === tab }} onPress={() => setSelected(tab)} style={[styles.tab, selected === tab && styles.activeTab]}><Text style={[styles.tabText, selected === tab && styles.activeTabText]}>{tabLabels[tab]}</Text></Pressable>)}</View>{loading ? <View style={styles.loading}><ActivityIndicator color={colors.primary} /></View> : error ? <EmptyState icon="cloud-offline-outline" title="We couldn't load your bookings." description="Please try again." actionLabel="Try Again" onAction={() => void load()} /> : <FlatList data={visibleBookings} keyExtractor={(item) => item.id} contentContainerStyle={visibleBookings.length ? styles.list : styles.emptyList} renderItem={({ item }) => <BookingCard booking={item} category={selected} onPress={() => router.push(`/booking-details?id=${item.id}` as Href)} onBookAgain={selected === 'completed' || selected === 'cancelled' ? () => void bookAgain(item.id) : undefined} onDirections={selected === 'upcoming' ? () => { const facility = mockParkingFacilities.find((itemFacility) => itemFacility.id === item.facilityId); if (facility) void openParkingDirections(facility); } : undefined} />} ListEmptyComponent={<EmptyState icon={selected === 'cancelled' ? 'close-circle-outline' : 'calendar-outline'} title={emptyCopy[selected][0]} description={emptyCopy[selected][1]} actionLabel={selected === 'upcoming' ? 'Find Parking' : undefined} onAction={selected === 'upcoming' ? () => router.push('/results' as Href) : undefined} />} />}</View>;
}
const styles = StyleSheet.create({ screen: { flex: 1, paddingHorizontal: spacing.lg, backgroundColor: colors.background }, search: { height: 46, flexDirection: 'row', alignItems: 'center', gap: spacing.sm, paddingHorizontal: spacing.md, borderRadius: radius.md, backgroundColor: colors.surface, marginTop: spacing.sm }, searchInput: { flex: 1, ...typography.bodySmall, color: colors.textPrimary }, tabs: { flexDirection: 'row', marginTop: spacing.lg, borderBottomWidth: 1, borderBottomColor: colors.borderSubtle }, tab: { flex: 1, alignItems: 'center', paddingBottom: spacing.md, borderBottomWidth: 2, borderBottomColor: 'transparent' }, activeTab: { borderBottomColor: colors.primary }, tabText: { ...typography.captionStrong, color: colors.textTertiary }, activeTabText: { color: colors.primary }, list: { gap: spacing.md, paddingVertical: spacing.lg, paddingBottom: spacing.xxxl }, emptyList: { flexGrow: 1 }, loading: { flex: 1, justifyContent: 'center' } });
