import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { AppHeader } from '@/components/layout/app-header';
import { useAppStore } from '@/store/app-store';
import { colors, radius, spacing, typography } from '@/theme/tokens';

const groups = [{ title: 'PARKING', rows: [['My Vehicles', 'car-outline', '/vehicles'], ['My Bookings', 'calendar-outline', '/bookings'], ['Saved Parking', 'heart-outline', '/saved-parking'], ['Saved Places', 'location-outline', '/saved-places']] }, { title: 'PAYMENTS', rows: [['Wallet', 'wallet-outline', '/wallet'], ['Offers & Coupons', 'pricetag-outline', '/offers']] }, { title: 'PREFERENCES', rows: [['Notifications', 'notifications-outline', '/notifications'], ['Settings', 'settings-outline', '/settings']] }, { title: 'SUPPORT', rows: [['Help & Support', 'help-circle-outline', '/help'], ['Terms & Conditions', 'document-text-outline', '/legal?type=terms'], ['Privacy Policy', 'shield-checkmark-outline', '/legal?type=privacy'], ['About ParkEase', 'information-circle-outline', '/about']] }];
export default function ProfileScreen() { const { session, logout } = useAppStore(); const user = session?.user; const confirmLogout = () => Alert.alert('Log out of ParkEase?', 'Your local bookings and preferences will stay on this device.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Log Out', style: 'destructive', onPress: () => void logout().then(() => router.replace('/' as never)) }]); return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><AppHeader eyebrow="Account" title="Profile" /><View style={styles.identity}><View style={styles.avatar}><Text style={styles.initial}>{user?.name.charAt(0).toUpperCase() ?? 'P'}</Text></View><View style={styles.flex}><Text style={styles.name}>{user?.name ?? 'ParkEase user'}</Text><Text style={styles.meta}>{user?.phone ?? '—'}</Text><Text numberOfLines={1} style={styles.meta}>{user?.email ?? 'Add your email address'}</Text></View></View><Pressable accessibilityRole="button" onPress={() => router.push('/edit-profile' as never)} style={({ pressed }) => [styles.edit, pressed && styles.pressed]}><Text style={styles.editText}>Edit Profile</Text><Ionicons name="chevron-forward" size={17} color={colors.primary} /></Pressable>{groups.map((group) => <View key={group.title}><Text style={styles.heading}>{group.title}</Text><View style={styles.card}>{group.rows.map(([label, icon, route], index) => <Pressable key={label} accessibilityRole="button" accessibilityLabel={label} onPress={() => router.push(route as never)} style={({ pressed }) => [styles.row, index < group.rows.length - 1 && styles.divider, pressed && styles.pressed]}><View style={styles.rowIcon}><Ionicons name={icon as keyof typeof Ionicons.glyphMap} size={19} color={colors.primary} /></View><Text style={styles.rowText}>{label}</Text><Ionicons name="chevron-forward" size={18} color={colors.textTertiary} /></Pressable>)}</View></View>)}<Text style={styles.heading}>ACCOUNT</Text><View style={styles.card}><Pressable accessibilityRole="button" onPress={confirmLogout} style={({ pressed }) => [styles.row, pressed && styles.pressed]}><View style={styles.dangerIcon}><Ionicons name="log-out-outline" size={19} color={colors.error} /></View><Text style={[styles.rowText, { color: colors.error }]}>Log Out</Text></Pressable></View></ScrollView>; }
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.background }, content: { padding: spacing.lg, gap: spacing.md, paddingBottom: spacing.xxxl }, identity: { flexDirection: 'row', gap: spacing.md, alignItems: 'center' }, avatar: { width: 58, height: 58, borderRadius: radius.full, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.primary }, initial: { ...typography.title2, color: colors.textOnPrimary }, flex: { flex: 1 }, name: { ...typography.title3, color: colors.textPrimary }, meta: { ...typography.bodySmall, color: colors.textSecondary, marginTop: 2 }, edit: { minHeight: 48, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 4, borderRadius: radius.md, backgroundColor: colors.primarySoft }, editText: { ...typography.bodyStrong, color: colors.primary }, heading: { ...typography.captionStrong, color: colors.textTertiary, marginTop: spacing.sm, letterSpacing: 0.55 }, card: { borderWidth: 1, borderColor: colors.borderSubtle, borderRadius: radius.lg, overflow: 'hidden', backgroundColor: colors.surface }, row: { minHeight: 56, flexDirection: 'row', alignItems: 'center', gap: spacing.md, paddingHorizontal: spacing.md }, divider: { borderBottomWidth: 1, borderBottomColor: colors.borderSubtle }, rowIcon: { width: 28, alignItems: 'center' }, dangerIcon: { width: 28, alignItems: 'center' }, rowText: { ...typography.bodyStrong, color: colors.textPrimary, flex: 1 }, pressed: { opacity: 0.82 } });
