import { Ionicons } from '@expo/vector-icons';
import { useFocusEffect } from 'expo-router';
import { useCallback, useState } from 'react';
import { ActivityIndicator, FlatList, Modal, Pressable, StyleSheet, Text, View } from 'react-native';
import { AppHeader } from '@/components/layout/app-header';
import { FormTextInput } from '@/components/ui/form-text-input';
import { PrimaryButton } from '@/components/ui/primary-button';
import { walletService } from '@/services/wallet-service';
import { Wallet, WalletTransaction } from '@/types/domain';
import { formatBookingDateTime } from '@/utils/booking-time';
import { formatCurrency } from '@/utils/parking-formatters';
import { colors, radius, shadows, spacing, typography } from '@/theme/tokens';

const presets = [100, 250, 500, 1000];

export default function WalletScreen() {
  const [wallet, setWallet] = useState<Wallet | null>(null); const [transactions, setTransactions] = useState<WalletTransaction[]>([]);
  const [add, setAdd] = useState(false); const [amount, setAmount] = useState('500'); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { const [saved, history] = await Promise.all([walletService.getWallet(), walletService.getTransactions()]); setWallet(saved); setTransactions(history); }, []);
  useFocusEffect(useCallback(() => { void load(); }, [load]));
  const topUp = async () => { const value = Number(amount); if (!Number.isFinite(value) || value < 50 || value > 10000) return; setBusy(true); await walletService.creditWallet(value, { type: 'topUp', title: 'Wallet top-up', description: 'Mock funds added to your ParkEase Wallet' }); await load(); setBusy(false); setAdd(false); };
  return <View style={styles.screen}>
    <AppHeader eyebrow="Payments" title="Wallet" />
    <View style={styles.balanceCard}><View style={styles.balanceTop}><Text style={styles.balanceLabel}>Available balance</Text><Ionicons name="wallet-outline" size={21} color={colors.textOnPrimary} /></View><Text accessibilityLabel={`Wallet balance ${formatCurrency(wallet?.balance ?? 0)}`} style={styles.balance}>{formatCurrency(wallet?.balance ?? 0)}</Text><Text style={styles.balanceHint}>Ready to use for parking checkout</Text></View>
    <PrimaryButton label="Add Money" icon="add-circle-outline" onPress={() => setAdd(true)} />
    <Text style={styles.historyTitle}>Recent transactions</Text>
    {wallet ? <FlatList data={transactions} keyExtractor={(item) => item.id} contentContainerStyle={transactions.length ? styles.list : styles.empty} renderItem={({ item }) => <TransactionRow item={item} />} ListEmptyComponent={<View style={styles.emptyState}><Ionicons name="receipt-outline" size={24} color={colors.textTertiary} /><Text style={styles.emptyText}>No wallet transactions yet.</Text></View>} /> : <ActivityIndicator color={colors.primary} />}
    <Modal visible={add} transparent animationType="slide" onRequestClose={() => setAdd(false)}><View style={styles.modal}><View style={styles.sheet}><View style={styles.handle} /><Text style={styles.sheetTitle}>Add Money</Text><Text style={styles.sheetText}>Add mock funds to use during parking checkout.</Text><View style={styles.presets}>{presets.map((value) => <Pressable key={value} accessibilityRole="button" onPress={() => setAmount(String(value))} style={({ pressed }) => [styles.preset, amount === String(value) && styles.presetSelected, pressed && styles.pressed]}><Text style={[styles.presetText, amount === String(value) && styles.presetTextSelected]}>{formatCurrency(value)}</Text></Pressable>)}</View><FormTextInput label="Custom amount" prefix="₹" accessibilityLabel="Custom top-up amount" value={amount} onChangeText={setAmount} keyboardType="number-pad" helperText="Minimum ₹50 · maximum ₹10,000" /><PrimaryButton label="Add Money" isLoading={busy} onPress={() => void topUp()} /><PrimaryButton label="Cancel" variant="secondary" onPress={() => setAdd(false)} /></View></View></Modal>
  </View>;
}

function TransactionRow({ item }: { item: WalletTransaction }) { const credit = item.direction === 'credit'; return <View style={styles.transaction}><View style={[styles.transactionIcon, credit ? styles.creditIcon : styles.debitIcon]}><Ionicons name={credit ? 'arrow-down-outline' : 'arrow-up-outline'} size={18} color={credit ? colors.success : colors.primary} /></View><View style={styles.flex}><Text numberOfLines={1} style={styles.transactionTitle}>{item.title}</Text><Text numberOfLines={1} style={styles.transactionDetail}>{item.description}</Text><Text style={styles.time}>{formatBookingDateTime(item.createdAt)}</Text></View><View style={styles.amountBlock}><Text style={[styles.direction, { color: credit ? colors.success : colors.textSecondary }]}>{credit ? 'CREDIT' : 'DEBIT'}</Text><Text style={[styles.transactionAmount, { color: credit ? colors.success : colors.textPrimary }]}>{credit ? '+' : '-'}{formatCurrency(item.amount)}</Text></View></View>; }

const styles = StyleSheet.create({ screen: { flex: 1, paddingHorizontal: spacing.lg, gap: spacing.md, backgroundColor: colors.background }, balanceCard: { padding: spacing.xl, borderRadius: radius.xl, borderWidth: 1, borderColor: colors.primaryPressed, backgroundColor: colors.primary, ...shadows.card }, balanceTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, balanceLabel: { ...typography.bodyStrong, color: colors.textOnPrimary }, balance: { ...typography.display, color: colors.textOnPrimary, marginTop: spacing.lg }, balanceHint: { ...typography.bodySmall, color: colors.primaryTextSoft, marginTop: spacing.xs }, historyTitle: { ...typography.title3, color: colors.textPrimary, marginTop: spacing.md }, list: { gap: 0, paddingBottom: spacing.xxxl, borderRadius: radius.lg, overflow: 'hidden', backgroundColor: colors.surface }, empty: { flexGrow: 1 }, emptyState: { alignItems: 'center', gap: spacing.sm, paddingTop: spacing.xxl }, emptyText: { ...typography.bodySmall, color: colors.textSecondary }, transaction: { minHeight: 76, flexDirection: 'row', alignItems: 'center', gap: spacing.sm, paddingHorizontal: spacing.md, borderBottomWidth: 1, borderBottomColor: colors.borderSubtle, backgroundColor: colors.surface }, transactionIcon: { width: 36, height: 36, alignItems: 'center', justifyContent: 'center', borderRadius: radius.full }, creditIcon: { backgroundColor: colors.successSoft }, debitIcon: { backgroundColor: colors.primarySoft }, flex: { flex: 1 }, transactionTitle: { ...typography.bodyStrong, color: colors.textPrimary }, transactionDetail: { ...typography.caption, color: colors.textSecondary, marginTop: 2 }, time: { ...typography.caption, color: colors.textTertiary, marginTop: 2 }, amountBlock: { alignItems: 'flex-end' }, direction: { ...typography.captionStrong, letterSpacing: 0.35 }, transactionAmount: { ...typography.bodyStrong, marginTop: 2 }, modal: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(17,24,39,0.35)' }, sheet: { gap: spacing.md, padding: spacing.xl, borderTopLeftRadius: radius.xl, borderTopRightRadius: radius.xl, backgroundColor: colors.surface }, handle: { alignSelf: 'center', width: 36, height: 4, borderRadius: radius.full, backgroundColor: colors.border }, sheetTitle: { ...typography.title2, color: colors.textPrimary }, sheetText: { ...typography.bodySmall, color: colors.textSecondary }, presets: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }, preset: { minWidth: 72, paddingVertical: spacing.sm, paddingHorizontal: spacing.md, alignItems: 'center', borderWidth: 1, borderColor: colors.border, borderRadius: radius.full, backgroundColor: colors.surface }, presetSelected: { borderColor: colors.primary, backgroundColor: colors.primary }, presetText: { ...typography.captionStrong, color: colors.textPrimary }, presetTextSelected: { color: colors.textOnPrimary }, pressed: { opacity: 0.82 } });
