import { Ionicons } from '@expo/vector-icons';
import { Href, router } from 'expo-router';
import { memo, useEffect, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { ParkingFacility } from '@/types/domain';
import { favoritesService } from '@/services/favorites-service';
import { formatAvailability, formatDistance, formatPricePerHour, getAvailabilityStatus } from '@/utils/parking-formatters';
import { colors, radius, shadows, spacing, typography } from '@/theme/tokens';

const featureIcons: Partial<Record<ParkingFacility['features'][number], keyof typeof Ionicons.glyphMap>> = { covered: 'shield-checkmark-outline', evCharging: 'flash-outline', cctv: 'videocam-outline', twentyFourHours: 'time-outline' };
export const ParkingCard = memo(function ParkingCard({ facility, variant = 'compact' }: { facility: ParkingFacility; variant?: 'compact' | 'list' }) {
  const [isFavorite, setIsFavorite] = useState(false);
  useEffect(() => { void favoritesService.isFavorite(facility.id).then(setIsFavorite); }, [facility.id]);
  const availability = getAvailabilityStatus(facility);
  const availabilityColor = availability === 'available' ? colors.success : availability === 'limited' ? colors.warning : colors.textTertiary;
  return <View style={[styles.card, variant === 'list' && styles.listCard]}><Pressable accessibilityRole="button" accessibilityLabel={`View ${facility.name}`} accessibilityHint="Opens parking details" onPress={() => router.push(`/parking/${facility.id}` as Href)} style={({ pressed }) => [styles.cardPressable, variant === 'list' && styles.listPressable, pressed && styles.pressed]}><View style={[styles.thumbnail, variant === 'list' && styles.listThumbnail]}><Ionicons name="car-sport" size={31} color={colors.primary} /><View style={styles.thumbnailBadge}><Ionicons name="star" size={11} color={colors.warning} /><Text style={styles.rating}>{facility.rating.toFixed(1)}</Text></View></View><View style={styles.details}><View style={styles.nameRow}><Text numberOfLines={1} style={styles.name}>{facility.name}</Text></View><Text style={styles.meta}>{formatDistance(facility.distanceKm)} · {facility.walkingMinutes} min walk{variant === 'list' ? ` · ${facility.reviewCount} reviews` : ''}</Text><View style={styles.featureRow}>{facility.features.slice(0, variant === 'list' ? 3 : 2).map((feature) => featureIcons[feature] ? <View key={feature} style={styles.feature}><Ionicons name={featureIcons[feature]} size={13} color={colors.textSecondary} /></View> : null)}{variant === 'list' ? <Text style={styles.type}>{facility.parkingType}</Text> : null}</View><View style={styles.footer}><View style={styles.status}><View style={[styles.dot, { backgroundColor: availabilityColor }]} /><Text style={[styles.availability, { color: availabilityColor }]}>{formatAvailability(facility)}</Text></View><Text style={styles.price}>{formatPricePerHour(facility.pricePerHour)}</Text></View></View></Pressable><Pressable accessibilityRole="button" accessibilityLabel={isFavorite ? `Remove ${facility.name} from saved parking` : `Save ${facility.name}`} accessibilityState={{ selected: isFavorite }} hitSlop={spacing.sm} onPress={() => void favoritesService.toggleFavorite(facility.id).then(setIsFavorite)} style={styles.favorite}><Ionicons name={isFavorite ? 'heart' : 'heart-outline'} size={20} color={isFavorite ? colors.error : colors.textSecondary} /></Pressable></View>;
});
const styles = StyleSheet.create({ card: { width: 292, minHeight: 154, borderRadius: radius.lg, backgroundColor: colors.surface, ...shadows.card }, listCard: { width: '100%', minHeight: 166 }, cardPressable: { minHeight: 154, padding: spacing.md, flexDirection: 'row', gap: spacing.md, borderRadius: radius.lg }, listPressable: { minHeight: 166 }, pressed: { opacity: 0.86, transform: [{ scale: 0.99 }] }, favorite: { position: 'absolute', top: spacing.md, right: spacing.md, width: 28, height: 28, alignItems: 'center', justifyContent: 'center' }, thumbnail: { width: 90, borderRadius: radius.md, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.primarySoft }, listThumbnail: { width: 96 }, thumbnailBadge: { position: 'absolute', bottom: 7, flexDirection: 'row', alignItems: 'center', gap: 3, paddingHorizontal: 6, paddingVertical: 3, borderRadius: radius.full, backgroundColor: colors.surface }, rating: { ...typography.captionStrong, color: colors.textPrimary }, details: { flex: 1, justifyContent: 'space-between' }, nameRow: { flexDirection: 'row', alignItems: 'center', paddingRight: spacing.lg }, name: { ...typography.bodyStrong, color: colors.textPrimary, flex: 1 }, meta: { ...typography.caption, color: colors.textSecondary }, featureRow: { flexDirection: 'row', alignItems: 'center', gap: 5 }, feature: { width: 24, height: 20, justifyContent: 'center', alignItems: 'center', borderRadius: radius.sm, backgroundColor: colors.surfaceMuted }, type: { ...typography.captionStrong, color: colors.textSecondary, textTransform: 'capitalize' }, footer: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, status: { flexDirection: 'row', alignItems: 'center', gap: 5, flex: 1 }, dot: { width: 7, height: 7, borderRadius: radius.full }, availability: { ...typography.captionStrong }, price: { ...typography.bodyStrong, color: colors.textPrimary } });
