import { Ionicons } from '@expo/vector-icons';
import { Href, router } from 'expo-router';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { ParkingFacility } from '@/types/domain';
import { formatAvailability, formatDistance, formatPricePerHour } from '@/utils/parking-formatters';
import { colors, radius, shadows, spacing, typography } from '@/theme/tokens';

export function ParkingPreviewSheet({ facility }: { facility: ParkingFacility }) { return <View style={styles.sheet}><View style={styles.handle} /><View style={styles.body}><View style={styles.thumbnail}><Ionicons name="car-sport" size={24} color={colors.primary} /></View><View style={styles.copy}><Text numberOfLines={1} style={styles.name}>{facility.name}</Text><Text style={styles.meta}>{formatDistance(facility.distanceKm)} · ★ {facility.rating.toFixed(1)} · {formatAvailability(facility)}</Text><Text style={styles.price}>{formatPricePerHour(facility.pricePerHour)}</Text></View><Pressable accessibilityRole="button" accessibilityLabel={`View ${facility.name}`} onPress={() => router.push(`/parking/${facility.id}` as Href)} style={styles.arrow}><Ionicons name="arrow-forward" size={19} color={colors.primary} /></Pressable></View></View>; }
const styles = StyleSheet.create({ sheet: { borderTopLeftRadius: radius.xl, borderTopRightRadius: radius.xl, backgroundColor: colors.surface, ...shadows.elevated }, handle: { width: 38, height: 4, alignSelf: 'center', borderRadius: radius.full, backgroundColor: colors.border, marginTop: spacing.sm }, body: { minHeight: 110, padding: spacing.md, flexDirection: 'row', alignItems: 'center', gap: spacing.md }, thumbnail: { width: 58, height: 58, alignItems: 'center', justifyContent: 'center', borderRadius: radius.md, backgroundColor: colors.primarySoft }, copy: { flex: 1, gap: 3 }, name: { ...typography.bodyStrong, color: colors.textPrimary }, meta: { ...typography.caption, color: colors.textSecondary }, price: { ...typography.bodyStrong, color: colors.textPrimary }, arrow: { width: 42, height: 42, alignItems: 'center', justifyContent: 'center', borderRadius: radius.full, backgroundColor: colors.primarySoft } });
