import { Ionicons } from '@expo/vector-icons';
import { useState } from 'react';
import { Modal, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { ParkingFacility, ParkingFeature, ParkingFilters, ParkingPriceRange, ParkingType } from '@/types/domain';
import { getParkingResults, priceRangeLabels } from '@/utils/parking-results';
import { colors, radius, spacing, typography } from '@/theme/tokens';

const featureOptions: { value: ParkingFeature; label: string; icon: keyof typeof Ionicons.glyphMap }[] = [{ value: 'covered', label: 'Covered', icon: 'shield-checkmark-outline' }, { value: 'evCharging', label: 'EV charging', icon: 'flash-outline' }, { value: 'cctv', label: 'CCTV', icon: 'videocam-outline' }, { value: 'security', label: 'Security', icon: 'lock-closed-outline' }, { value: 'accessible', label: 'Accessible', icon: 'accessibility-outline' }, { value: 'valet', label: 'Valet', icon: 'key-outline' }];
const typeOptions: { value: ParkingType; label: string }[] = [{ value: 'mall', label: 'Mall' }, { value: 'commercial', label: 'Commercial' }, { value: 'metro', label: 'Metro' }, { value: 'airport', label: 'Airport' }, { value: 'hospital', label: 'Hospital' }, { value: 'street', label: 'Street' }];
const priceOptions = Object.entries(priceRangeLabels) as [ParkingPriceRange, string][];

function Choice({ label, selected, onPress }: { label: string; selected: boolean; onPress: () => void }) { return <Pressable accessibilityRole="button" accessibilityState={{ selected }} onPress={onPress} style={[styles.choice, selected && styles.choiceSelected]}><Text style={[styles.choiceText, selected && styles.choiceTextSelected]}>{label}</Text></Pressable>; }
function toggle<T>(values: T[], value: T) { return values.includes(value) ? values.filter((item) => item !== value) : [...values, value]; }

export function FilterSheet({ filters, facilities, onClose, onApply, onClear }: { filters: ParkingFilters; facilities: ParkingFacility[]; onClose: () => void; onApply: (filters: ParkingFilters) => void; onClear: () => void; }) {
  const [draft, setDraft] = useState(filters);
  const count = getParkingResults(facilities, draft, 'recommended').length;
  const update = <K extends keyof ParkingFilters>(key: K, value: ParkingFilters[K]) => setDraft((current) => ({ ...current, [key]: value }));
  const clear = () => { const blank: ParkingFilters = { distanceKm: null, priceRange: null, availability: null, minimumRating: null, features: [], parkingTypes: [] }; setDraft(blank); onClear(); };
  return <Modal transparent animationType="slide" onRequestClose={onClose}><View style={styles.scrim}><Pressable style={StyleSheet.absoluteFill} onPress={onClose} /><View style={styles.sheet}><View style={styles.handle} /><View style={styles.header}><Text style={styles.title}>Filter parking</Text><Pressable accessibilityRole="button" onPress={onClose} hitSlop={spacing.sm}><Ionicons name="close" size={24} color={colors.textPrimary} /></Pressable></View><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.body}>
      <Text style={styles.label}>Distance</Text><View style={styles.choices}>{[1, 3, 5, 10].map((value) => <Choice key={value} label={`Within ${value} km`} selected={draft.distanceKm === value} onPress={() => update('distanceKm', draft.distanceKm === value ? null : value)} />)}</View>
      <Text style={styles.label}>Price per hour</Text><View style={styles.choices}>{priceOptions.map(([value, label]) => <Choice key={value} label={label} selected={draft.priceRange === value} onPress={() => update('priceRange', draft.priceRange === value ? null : value)} />)}</View>
      <Text style={styles.label}>Availability</Text><View style={styles.choices}>{[['availableNow', 'Available now'], ['notFull', 'Not full']].map(([value, label]) => <Choice key={value} label={label} selected={draft.availability === value} onPress={() => update('availability', draft.availability === value ? null : value as ParkingFilters['availability'])} />)}</View>
      <Text style={styles.label}>Minimum rating</Text><View style={styles.choices}>{[4, 4.5].map((value) => <Choice key={value} label={`${value.toFixed(1)}+ rated`} selected={draft.minimumRating === value} onPress={() => update('minimumRating', draft.minimumRating === value ? null : value)} />)}</View>
      <Text style={styles.label}>Features</Text><View style={styles.choices}>{featureOptions.map((option) => <Pressable key={option.value} accessibilityRole="button" accessibilityState={{ selected: draft.features.includes(option.value) }} onPress={() => update('features', toggle(draft.features, option.value))} style={[styles.choice, draft.features.includes(option.value) && styles.choiceSelected]}><Ionicons name={option.icon} size={15} color={draft.features.includes(option.value) ? colors.textOnPrimary : colors.textSecondary} /><Text style={[styles.choiceText, draft.features.includes(option.value) && styles.choiceTextSelected]}>{option.label}</Text></Pressable>)}</View>
      <Text style={styles.label}>Parking type</Text><View style={styles.choices}>{typeOptions.map((option) => <Choice key={option.value} label={option.label} selected={draft.parkingTypes.includes(option.value)} onPress={() => update('parkingTypes', toggle(draft.parkingTypes, option.value))} />)}</View>
    </ScrollView><View style={styles.footer}><Pressable accessibilityRole="button" onPress={clear} style={styles.clear}><Text style={styles.clearText}>Clear all</Text></Pressable><Pressable accessibilityRole="button" onPress={() => { onApply(draft); onClose(); }} style={styles.apply}><Text style={styles.applyText}>Show {count} result{count === 1 ? '' : 's'}</Text></Pressable></View></View></View></Modal>;
}
const styles = StyleSheet.create({ scrim: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(17,24,39,0.38)' }, sheet: { maxHeight: '88%', borderTopLeftRadius: radius.xl, borderTopRightRadius: radius.xl, backgroundColor: colors.background }, handle: { alignSelf: 'center', width: 38, height: 4, borderRadius: radius.full, marginTop: spacing.sm, backgroundColor: colors.border }, header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: spacing.lg, paddingVertical: spacing.md }, title: { ...typography.title2, color: colors.textPrimary }, body: { paddingHorizontal: spacing.lg, paddingBottom: spacing.xl, gap: spacing.sm }, label: { ...typography.bodyStrong, color: colors.textPrimary, marginTop: spacing.md }, choices: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }, choice: { minHeight: 38, flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: spacing.md, borderWidth: 1, borderColor: colors.border, borderRadius: radius.full, backgroundColor: colors.surface }, choiceSelected: { borderColor: colors.primary, backgroundColor: colors.primary }, choiceText: { ...typography.captionStrong, color: colors.textSecondary }, choiceTextSelected: { color: colors.textOnPrimary }, footer: { flexDirection: 'row', gap: spacing.md, padding: spacing.lg, borderTopWidth: 1, borderColor: colors.borderSubtle, backgroundColor: colors.surface }, clear: { minHeight: 48, alignItems: 'center', justifyContent: 'center', paddingHorizontal: spacing.md }, clearText: { ...typography.bodyStrong, color: colors.primary }, apply: { flex: 1, minHeight: 48, alignItems: 'center', justifyContent: 'center', borderRadius: radius.md, backgroundColor: colors.primary }, applyText: { ...typography.bodyStrong, color: colors.textOnPrimary } });
